var config_byValues_en = {
	"species_record_tooltip": "Click on a cell to view more details about the record",
	"islands_record_tooltip": "Click on a cell to pan to that island on the map",
	"no_filter": "No search filters chosen.  Please select items from the Search pane to filter by ...",
	"Error selecting the item in the data table": "Error selecting the item in the data table",
	"Download": "Download",
	"Export": "Export",
	"Export to PDF": "Export to PDF",
	"Export to CSV": "Export to CSV",	
	"Exporting to PDF": "Exporting to PDF",
	"Exporting to CSV": "Exporting to CSV",
	"Download PDF": "Download PDF",
	"Download CSV": "Download CSV",
	"Processing": "Processing",
	"No thumbnail images found": "No thumbnail images found",
	"Filter": "Filter",
	"Species Details": "Species Details",
	"Location Details": "Location Details",
	"Eradication Details": "Eradication Details",
	"Contact Details": "Contact Details",
	"Common Name": "Common Name",
	"Scientific Name": "Scientific Name",
	"Type (Animal)": "Type (Animal)",
	"Year of Introduction": "Year of Introduction",
	"Latitude": "Latitude",
	"Longitude": "Longitude",
	"Status (Eradication)": "Status (Eradication)",
	"Primary Eradication Method": "Primary Eradication Method",
	"Secondary Eradication Method": "Secondary Eradication Method",
	"Tertiary Eradication Method": "Tertiary Eradication Method",
	"Eradication Start Date": "Eradication Start Date",
	"Eradication End Date": "Eradication End Date",	
	"Primary Baiting Method": "Primary Baiting Method",
	"Secondary Baiting Method": "Secondary Baiting Method",
	"Eradication Method Details": "Eradication Method Details",
	"Trapping Method Details": "Trapping Method Details",
	"Method Description": "Method Description",
	"Primary Toxicant": "Primary Toxicant",
	"Secondary Toxicant": "Secondary Toxicant",
	"Cost": "Cost",
	"Eradication Contact": "Eradication Contact",
	"Contact Email": "Contact Email",
	"Contact Organization": "Contact Organization",
	"Organization Website": "Organization Website",
	"Island Code": "Island Code",
	"Island Name": "Island Name",
	"Name": "Name",
	"Coordinates": "Coordinates",
	"Region": "Region",
	"Country": "Country",
	"Archipelago": "Archipelago",
	"Area (sq km)": "Area (sq km)",	
	"Human Population": "Human Population",
	"Invasive Species": "Invasive Species",
	"Threatened Species": "Threatened Species",
	"Threatened": "Threatened",
	"eradication": "eradication",
	"eradications": "eradications",
	"None": "None",
	"none": "none",
	"yes": "yes",
	"no": "no",	
	"Populations": "Populations",
	"populations": "populations",
	"population": "population",
	"no common name": "no common name",
	"unknown": "unknown",
	"Status": "Status",
	"Year": "Year",
	" -- all -- ": " -- all -- ",
	"Arctic Ocean - North Canada": "Arctic Ocean - North Canada",
	"Atlantic Ocean - North": "Atlantic Ocean - North",
	"Atlantic Ocean - South": "Atlantic Ocean - South",
	"Baltic sea": "Baltic sea",
	"Caribbean": "Caribbean",
	"Indian Ocean - East": "Indian Ocean - East",
	"Indian Ocean - West": "Indian Ocean - West",
	"Mediterranean": "Mediterranean",
	"Nusantarian Sea": "Nusantarian Sea",
	"Pacific Ocean - North East": "Pacific Ocean - North East",
	"Pacific Ocean - North West": "Pacific Ocean - North West",
	"Pacific Ocean - South East": "Pacific Ocean - South East",
	"Pacific Ocean - South West": "Pacific Ocean - South West",
	"Rodent": "Rodent",
	"Ungulate": "Ungulate",
	"Cat": "Cat",
	"Rabbit and Hare": "Rabbit and Hare",
	"Mongoose and Weasel": "Mongoose and Weasel",
	"Dog and Fox": "Dog and Fox",
	"Mammal (Other)": "Mammal (Other)",
	"Reptile": "Reptile",
	"Bird": "Bird",
	"Being Confirmed": "Being Confirmed",
	"In Progress": "In Progress",
	"Incomplete": "Incomplete",
	"Failed": "Failed",
	"Planned": "Planned",
	"Successful": "Successful",
	"Successful (reinvaded)": "Successful (reinvaded)",
	"Unknown": "Unknown",
	"Incursion": "Incursion",
	"Research or Trial": "Research or Trial",
	"Disease": "Disease",
	"Hunting": "Hunting ",
	"Trapping": "Trapping",
	"Toxicant": "Toxicant",
	"Unknown": "Unknown",
	"Other": "Other"	
}

var config_byId_en = {
	"link_about": "About",
	"link_news": "News",
	"link_disclaimer": "Disclaimer",
	"link_terms": "Terms of Use",
	"link_help": "How to Help",
	"link_partners": "Partners",
	"link_contact": "Contact",
	"link_more": "More Info",
	"link_language": "Language",
	"language_english_text": "English",
	"language_spanish_text": "Spanish",
	"splash_language_text": "Language:",
	"splash_language_english": "English",
	"splash_language_spanish": "Spanish",
	"cisr": "built by the <a target=\"_blank\" href=\"http://spatial.cisr.ucsc.edu\">center for integrated spatial research (cisr)</a> @ <a target=\"_blank\" href=\"http://www.ucsc.edu\">ucsc</a>",
	"graphicText": "Graphic:",
	"rectangle": "... by Rectangle",
	"polygon":  "... by Polygon",
	"basemap_basic": "Basic",
	"basemap_satellite": "Satellite",
	"basemap_topographic": "Topographic",
	"printOptionsTextNode": "Export to PDF",
	"printButton": "Export",
	"csvOptionsTextNode": "Export to CSV",
	"csvButton": "Export",
	"regionSelect_label": "Region:",
	"countrySelect_label": "Country:",
	"islandSelect_label": "Island:",
	"invasiveTypeSelect_label": "Type:",
	"invasiveScientificSelect_label": "Scientific Name:",
	"invasiveCommonSelect_label": "Common Name:",
	"inv_sci_label": "Scientific Name",
	"inv_com_label": "Common Name",
	"eradicationStatusSelect_label": "Status:",
	"eradicationMethodSelect_label": "Primary Method:",
	"queryDefinition": "Filter:",
	"r_islands_text": "Number of islands: ",
	"invasives_sum_text": "eradications",
	"r_invasives_text": "Number of species: ",
	"r_type_animal": "Type (Animal)",
	"r_status_eradication": "Status (Eradication)",
	"islandTitle": "No Island Selected",
	"table_header_text": "Table",
	"noThumbnails": "No thumbnail images found",
	"aboutContent": "<span class=\"aboutHeader\">What is the Database of Island Invasive Species Eradications?</span><br/>Islands  are the epicenter of the current global extinction crisis and invasive  vertebrates are the leading cause of extinction on islands. Removing invasive  vertebrates from islands is a well-established tool to protect and restore  island ecosystems and prevent extinctions.<p>The  Database  of  Island Invasive Species Eradications compiles all of the historical and current invasive vertebrate eradications  on islands. Data from each project includes information on the island, methods  used in the eradication and contact information   for people knowledgeable about the eradication.</p><p>Our  hope is that the database will help by facilitating:</p><ul type=\"circle\"><li>Knowledge sharing: Improving transfer of knowledge between existing eradication practitioners, and providing contacts for each eradication to facilitate communication between experienced eradicators and those seeking assistance </li><li>Technique evaluation: Tracking eradication attempts to analyse where, how and who is undertaking these efforts, which techniques are successful and highlighting invasive species for which techniques are deficient. </li><li>Fund raising: this database is a valuable tool for fund raising by allowing practitioners to contextualize proposed island eradication projects against the global scope of this technique and historical eradication attempts. </li></ul><p>Maps and graphs are  examples of the kinds of analyses that can be done using the database. These  figures are based on the data available in the database as of 15 December,  2009. </p><b>Figure 1</b>. Cumulative number of successful eradications by decade, including totals for all carnivore, herbivore and omnivore eradications<br/><span class=\"center\"><img src=\"images/about-figure1.png\" /></span><br/><b>Figure 2</b>.  Total number of successful eradications for each of the main methods. Each method is further broken down by the category, carnivore, herbivore and omnivore, of the invasive species eradicated.</br><span class=\"center\"><img src=\"images/about-figure2.png\" /></span><br/><span class=\"aboutHeader\">How To Cite?</span> <br/>Island Conservation, 2012. Database of Island Invasive Species Eradications.  Hosted by the Center for Integrated Spatial Research.",
	"aboutReferenceHeader": "References",
	"errorContent": "Island Conservation endeavor to maintain the most accurate and up-to-date data at all times. However, if errors or omissions are identified, the user should notify Island Conservation <a href=\"mailto:science@islandconservation.org\">science@islandconservation.org</a> so that they can be corrected in future releases of the data. Please mark all correspondence: \"Database of Islands and Invasive Species Eradications\".",
	"disclaimerContent": "Island Conservation make no warranties or representations, express or implied, regarding the use of the material appearing in this dataset with regard to their correctness, reliability, accuracy, or otherwise. The material and geographic designations in this dataset do not imply the expressions of any opinion whatsoever on the part of Island Conservation concerning the legal status of any country, territory or area, nor concerning the delimitation of its frontiers or boundaries. Neither Island Conservation nor its affiliated or related entities or its content providers shall be responsible or liable to any person, firm or corporation for any loss, damage, injury, claim or liability of any kind or character based on or resulting from any information contained in the dataset. Island Conservation may update or make changes to the data provided at any time without notice; however, Island Conservation makes no commitment to update the information contained therein.",
	"termsOfUseContent": "<ol><li>The data are supplied only for conservation purposes, scientific analysis or research.</li><li>The recipient of the data will provide a full and appropriate acknowledgement and citation in any materials or publications derived in part or in whole from the data; relevant citation details will be provided with each dataset. For any publications making substantial use of the data, Island Conservation welcomes the opportunity for co-authorship, collaboration and to comment prior to publication. Expressions of interest can be sent to <a href=\"mailto:science@islandconservation.org?Subject=Publication(s)%20using%20DIISE\">science@islandconservation.org</a>.</li><li>Reproduction of the dataset or products derived from it, either whole or in part, for commercial purposes is prohibited without prior written permission from Island Conservation. For the purposes of these Terms of Use, “commercial purposes” means a) any use by, on behalf of, or to inform or assist the activities of, a commercial entity (an entity that operates ‘for profit’) or b) use by any non-profit entity for the purposes of revenue generation. If you require permission please contact <a href=\"mailto:science@islandconservation.org?Subject=Commercial%20use%20of%20DIISE\">science@islandconservation.org</a>.</li><li>The recipient will not publish the data in their original format, either whole or in part, on a website, FTP site, CD, memory stick or any other media. The recipient should provide a link to the original data source location on the IUCN Invasive Species Specialist Group website where appropriate.</li><li>Use of these data does not constitute endorsement by Island Conservation of any derived products, reports or analyses. The Island Conservation logo must not be used on any derived products, reports or analyses, or supporting materials, without express permission.</li><li>Use of these data does not constitute endorsement by Island Conservation of any derived products, reports or analyses. The Island Conservation logo must not be used on any derived products, reports or analyses, or supporting materials, without express permission.</li><li>Island Conservation reserves the right to comment on the accuracy of representation of the data in material produced by a recipient.</li><li>Island Conservation endeavor to maintain accurate and up-to-date data at all times, but can accept no responsibility for the consequences of errors or omissions in the data, for misuse of the data by any organization or individual, or for any damage done to computing systems into which the data are entered (see Disclaimer).</li><li>Either an electronic or two paper copies of all products published using data supplied by Island Conservation will be sent, free of charge, to the data authors via: Island Conservation, 100 Shaffer Road, Santa Cruz CA USA 95060 or via email to <a href=\"mailto:science@islandconservation.org?Subject=Publication(s)%20using%20DIISE\">science@islandconservation.org</a>.</li></ol>",
	"newsContent": "<b>Version 2012.3</b>: this database was last updated on December 5th 2012.",
	"partners_text": "People, organizations, and agencies that have helped develop the Database of Island Invasive Species Eradications"
}

var config_byDijitId_en = {
	"searchContentDiv": "Search",
	"resultsContentDiv": "Results",
	"islandContentDiv": "Island Details",
	"geography": "... by geographic location",
	"invasive": "... by invasive species",
	"eradication": "... by eradication detail",
	"searchButton": "Run Search", 
	"clearButton": "Clear Search",
	"infoDetails": "Island",
	"infoInvasive": "Eradication(s)",
	"eradicationDetails": "Details of Eradication Record",
	"about": "About the Database of Island Invasive Species Eradications",
	"news": "News",
	"disclaimer": "Disclaimer",
	"termsOfUse": "Terms of Use",
	"errors": "How to Help",
	"partners": "Partners",	
	"Letter": "Letter",	
	"searchTool_tooltip": "Click to open/close the custom Search window.",
	"resultsTool_tooltip": "Click to open/close the Results window.",
	"islandsTool_tooltip": "Click to open/close the Island Details window.",
	"csvTool_tooltip": "Click to export and download a .csv file of the results table.",
	"printTool_tooltip": "Click to export and download a high-resolution PDF.",
	"basemap_tooltip": "Click to change the underlying basemap.",
	"overview_tooltip": "Click to open/close the Overview Map window.",
	"zoomfull_tooltip": "Click to zoom out to the full extent of the map.",
	"zoomin_tooltip": "Click to zoom in to the map using a custom drawn extent.", 
	"splitter_tooltip": "Click and drag to increase or decrease the viewable table.",
	"close_tooltip": "Click to hide or show the table.",
	"results_tooltip": "Results from your custom search.",
	"island_tooltip": "Detailed information on a specific island.",
	"r_breeding_tooltip": "Shift + Click for complete definitions of Breeding Status.",
	"experts_tooltip": "Click for a list of contributing experts and the TIB data collection team.",
	"donate_tooltip": "Click to donate towards DIISE development via the Island Conservation Paypal site."	
}

var config_byValues_es = {
	"species_record_tooltip": "Pulse una celda para ver más detalles sobre el registro",
	"islands_record_tooltip": "Pulse una celda para desplazarse a la isla en el mapa",
	"no_filter": "No hay filtros de búsqueda elegido. Por favor, selecciona los artículos en el panel de búsqueda para filtrar por ...",
	"Error selecting the item in the data table": "Error de seleccionar el elemento de la tabla de datos",
	"Download": "Descargar",
	"Export": "Exportar",
	"Export to PDF": "Exportar a PDF",
	"Export to CSV": "Exportar a CSV",	
	"Exporting to PDF": "Exportar a PDF",
	"Exporting to CSV": "Exportar a CSV",
	"Download PDF": "Descargar PDF",
	"Download CSV": "Descargar CSV",
	"Processing": "Procesar",
	"No thumbnail images found": "No se encontraron imágenes 'thumbnail'",
	"Filter": "Filtro",
	"Graphic": "Grafico",
	"Species Details": "Especies Detalles",
	"Location Details": "Detalles de la ubicación",
	"Eradication Details": "Detalles de erradicación",
	"Contact Details": "Datos de contacto",
	"Common Name": "Nombre Común",
	"Scientific Name": "Nombre Científico",
	"Type (Animal)": "Tipo (Animal)",
	"Year of Introduction": "Año de Introducción",
	"Latitude": "Latitud",
	"Longitude": "Longitud",
	"Status (Eradication)": "Estado (Erradicación)",
	"Primary Eradication Method": "Erradicación Principal",
	"Secondary Eradication Method": "Erradicación Secundaria",
	"Tertiary Eradication Method": "Erradicación Terciario",
	"Eradication Start Date": "Fecha Inicio de Erradicación ",
	"Eradication End Date": "Fecha Final de Erradicación",	
	"Primary Baiting Method": "Cebo Primaria",
	"Secondary Baiting Method": "Cebo Secundaria",
	"Eradication Method Details": "Erradicación Método Detalles",
	"Trapping Method Details": "Método de Captura Detalles",
	"Method Description": "Método Descripción",
	"Primary Toxicant": "Tóxico Primaria",
	"Secondary Toxicant": "Tóxico Secundaria",
	"Cost": "Costo",
	"Eradication Contact": "Erradicación de Contacto",
	"Contact Email": "Correo Electrónico de Contacto",
	"Contact Organization": "Contacto Organización",
	"Organization Website": "Organización Sitio Web",
	"Island Code": "Código de Isla",
	"Island Name": "Nombre de Isla",
	"Name": "Nombre",
	"Coordinates": "Coordenadas",
	"Region": "Región",
	"Country": "País",
	"Archipelago": "Archipiélago",
	"Area (sq km)": "Area (sq km)",	
	"Human Population": "Población Humana",
	"Invasive Species": "Especies invasoras",
	"Threatened Species": "Especies amenazadas",
	"Threatened": "Amenazado",
	"eradication": "erradicación",
	"eradications": "erradicaciónes",
	"None": "Ninguno",
	"none": "ninguno",
	"yes": "si",
	"no": "no",	
	"Populations": "Poblaciónes",
	"populations": "poblaciónes",
	"population": "población",
	"no common name": "sin nombre Común",
	"unknown": "desconocido",
	"Status": "Estado",
	"Year": "Año",
	" -- all -- ": " -- todo -- ",
	"Arctic Ocean - North Canada": "Oceano Artico-Canada del Norte",
	"Atlantic Ocean - North": "Océano Atlántico - Norte",
	"Atlantic Ocean - South": "Océano Atlántico - Sur",
	"Baltic sea": "Mar Baltico",
	"Caribbean": "Caribe",
	"Indian Ocean - East": "Océano Indico - Este",
	"Indian Ocean - West": "Océano Indico- Oeste",
	"Mediterranean": "Mediterráneo",
	"Nusantarian Sea": "Mar Nusantario",
	"Pacific Ocean - North East": "Océano Pacífico - Noreste",
	"Pacific Ocean - North West": "Océano Pacifico - Noroeste",
	"Pacific Ocean - South East": "Océano Pacifico- Sureste",
	"Pacific Ocean - South West": "Océano Pacifico-Suroeste",
	"Rodent": "Roedor",
	"Ungulate": "Ungulado",
	"Cat": "Gato",
	"Rabbit and Hare": "Conejo y liebre",
	"Mongoose and Weasel": "Mangosta y Comadreja",
	"Dog and Fox": "Perro y Zorro",
	"Mammal (Other)": "Mamífero (otro)",
	"Reptile": "Reptil",
	"Bird": "Ave",
	"Being Confirmed": "Siendo Confirmado",
	"In Progress": "En Proceso",
	"Incomplete": "Incompleto",
	"Failed": "Fallido",
	"Planned": "Planificado",
	"Successful": "Existoso",
	"Successful (reinvaded)": "Existoso (reinvadido)",
	"Unknown": "Desconocido",
	"Incursion": "Incursion",
	"Research or Trial": "Investigación o prueba",
	"Disease": "Enfermedad",
	"Hunting": "Cacería ",
	"Trapping": "Trampa",
	"Toxicant": "Intoxicante",
	"Unknown": "Desconocido",
	"Other": "Otro"	
}

var config_byId_es = {
	"link_about": "Sobre",
	"link_news": "Noticias",
	"link_disclaimer": "Descargo de Responsabilidad",
	"link_terms": "Condiciones de Uso",
	"link_help": "Cómo Ayudar",
	"link_partners": "Socios",
	"link_contact": "Contacto",
	"link_more": "Más Info",
	"link_language": "Lengua",
	"language_english_text": "Inglés",
	"language_spanish_text": "Español",
	"splash_language_text": "Lengua:",
	"splash_language_english": "Inglés",
	"splash_language_spanish": "Español",
	"cisr": "construido por el <a target=\"_blank\" href=\"http://spatial.cisr.ucsc.edu\">centro para investigación espacial integrada (cisr)</a> @ <a target=\"_blank\" href=\"http://www.ucsc.edu\">ucsc</a>",
	"graphicText": "Grafico:",
	"rectangle": "... por Rectangulo",
	"polygon":  "... por Poligono",
	"basemap_basic": "Básico",
	"basemap_satellite": "Satélite",
	"basemap_topographic": "Topográfico",
	"printOptionsTextNode": "Exportar a PDF",
	"csvOptionsTextNode": "Exportar a CSV",
	"regionSelect_label": "Región:",
	"countrySelect_label": "Pais:",
	"islandSelect_label": "Isla:",
	"invasiveTypeSelect_label": "Tipo:",
	"invasiveScientificSelect_label": "Nombre Científico:",
	"invasiveCommonSelect_label": "Nombre Común:",
	"inv_sci_label": "Nombre Científico",
	"inv_com_label": "Nombre Común",
	"eradicationStatusSelect_label": "Estado:",
	"eradicationMethodSelect_label": "Método Principal:",
	"queryDefinition": "Filtro:",
	"r_islands_text": "Número de islas",
	"invasives_sum_text": "erradicaciónes",
	"r_invasives_text": "Número de especies",
	"r_type_animal": "Tipo (Animal)",
	"r_status_eradication": "Estado (Erradicación)",
	"islandTitle": "Ninguna Isla Seleccionada",
	"table_header_text": "Tabla",
	"noThumbnails": "No se encontraron imágenes 'thumbnail'...",
	"aboutContent": "<span class=\"aboutHeader\">Qué es la Base de Datos de Erradicaciones de Especies Invasoras?</span><br/>Las Islas son el epicentro de la actual crisis global de extinciones, siendo los vertebrados invasores la principal causa de extinciones en islas. La remoción de vertebrados invasores es una herramienta bien establecida para proteger y restaurar los ecosistemas insulares y prevenir extinciones.<p>La Base de Datos de Erradicaciones de Especies Invasoras en Islas agrega información histórica y actual sobre erradicaciones de vertebrados invasores en islas. Los datos de cada proyecto incluyen información sobre la isla, métodos usados en la erradicación e información de contacto de personas conocedoras sobre la erradicación.</p><p>Nuestra esperanza es que la base de datos facilitará:</p><ul type=\"circle\"><li>El intercambio de información: Mejorando la transferencia de conocimiento entre practicantes de métodos de erradicación. Proporcionando contactos sobre cada proyecto de erradicación para facilitar la comunicación entre erradicadores experimentados y aquellos en busca de asistencia. </li><li>Evaluación de técnicas: El seguimiento de los intentos de erradicación para analizar donde, como, y quien esta llevando a cabo estos esfuerzos; cuales técnicas son exitosas y resaltando las especies invasoras para las cuales las técnicas aún son deficientes.</li><li>Generación de fondos: Esta base de datos es una herramienta valiosa para recaudar fondos al permitirle a los practicantes conceptualizar  propuestas de proyectos de erradicacion en islas con base en un marco global de erradicaciones e información histórica sobre intentos de erradicación. </li></ul><p>Los mapas y gráficos presentados a continuación constituyen ejemplos de los tipos de análisis que pueden realizarse usando la base de datos. Estas figuras estan basadas en los datos disponibles al 15 de Diciembre del 2009.</p><b>Figura 1</b>. Número acumulativo de erradicaciones exitosas por década, incluyendo  totales para todos los carnívoros, herbívoros y omnívoros.<br/><span class=\"center\"><img src=\"images/about-figure1.png\" /></span><br/><b>Figure 2</b>.  Total de erradicaciones exitosas por cada método principal de captura. Cada método a su vez es dividido por categoría, carnívoro, herbívoro y omnívoro de especies invasoras erradicadas.</br><span class=\"center\"><img src=\"images/about-figure2.png\" /></span><br/><span class=\"aboutHeader\">Cómo citar?</span> <br/>Island Conservation, 2012. Database of Island Invasive Species Eradications.  Hosted by the Center for Integrated Spatial Research.",
	"aboutReferenceHeader": "Bibliografía",
	"errorContent": "\"Island Conservation\" se esfuerza por mantener datos precisos y actuales en todo momento. Sin embargo, de identificarse errores u omisiones, el usuario debe notificar a \"Island Conservation\" <a href=\"mailto:science@islandconservation.org\">science@islandconservation.org</a> para que estos puedan ser corregidos en la base de datos. Por favor marcar cualquier correspondencia con el titulo: \"Base de datos de islas y erradicaciones de especies invasoras\".",
	"disclaimerContent": "\"Island Conservation\" no establece garantías o representaciones, de forma expresa o implícita con respecto a la presición, veracidad o confiabilidad del material que aparece en la base de datos. El material y las designaciones geográficas en esta base de datos no reflejan la opinión de \"Island Conservation\" con respecto al estado legal de ningún país, territorio, o área, ni con respecto a la delimitación de su territorio o fronteras. Ni \"Island Conservation\", ni sus entidades afiliadas, o relacionadas,  ni quienes proporcionan el contenido de esta página se hacen responsables ante ninguna persona, firma o corporación por pérdida, daño, perjuicio, demanda o responsabilidad legal  como resultado de  información contenida en la base de datos. \"Island Conservation\" puede actualizar o realizar cambios a los datos proporcionados en cualquier momento y sin noticia previa; sin embargo, \"Island Conservation\" no se compromete a actualizar la información contenida en esta página de internet y sus bases de datos.",
	"termsOfUseContent": "<ol><li>Los datos son suministrados solo para propósitos de conservación, análisis científico o investigación.</li><li>El usuario de los datos otorgará completo y apropiado reconocimiento y hará la mención pertinente en cualquier material o publicaciones derivadas en parte o por entero de los datos aqui suministrados; se proporcionarán detalles relevantes sobre la forma apropiada de citar cada conjunto de datos . Para cualquier publicación que haga uso sustancial de los datos, \"Island Conservation\" da la bienvenida a la oportunidad de una co-autoría, colaboración, o comentario previo a la publicación. Expresiones de interés deben ser enviadas a <a href=\"mailto:science@islandconservation.org?Subject=Publication(s)%20using%20DIISE\">science@islandconservation.org</a>.</li><li>La reproducción de los datos o productos derivados de los mismos, de forma completa o parcial,  para propósitos comerciales, está prohibida sin permiso previo y/o por escrito de \"Island Conservation\". Para fines de estas condiciones de uso, \"propósitos comerciales\" significa a) cualquier uso por, o en beneficio de, o para informar o asistir las actividades de a) una entidad comercial (una entidad que opera \"con fines de lucro\") o b) uso por parte de una entidad sin fines de lucro con fines de generar recursos monetarios. Si usted requiere permiso por favor contacte a \"Island Conservation\" via correo electrónico a <a href=\"mailto:science@islandconservation.org?Subject=Commercial%20use%20of%20DIISE\">science@islandconservation.org</a>.</li><li>El usuario no publicará los datos en su formato original, ya sea completa o parcialmente, en una página de internet, sitio FTP, CD, barra de memoria o cualquier otro medio. El usuario debe proveer un vinculo a la ubicación original de los datos en la página de internet del \"Grupo Especialista en Especies Invasoras\" de la UICN cuando esto sea apropiado.</li><li>El uso de estos datos no constituye el endoso de \"Island Conservation\" a ningún producto derivado, reporte o análisis. El logo de \"Island Conservation\" no debe utilizarse en ningún producto derivado, reporte o análisis, o en materiales de apoyo sin permiso.</li><li>\"Island Conservation\" se reserva el derecho de comentar sobre la presición en la representación de los datos en cualquier material producido por el usuario </li><li>\"Island Conservation\" se esfuerza por mantener datos precisos y actualizados en todo momento, pero no se hace responsable por las consecuencias producto de errores u omisiones en los datos, mal uso de los datos por cualquier organización o individuo, o por daños a sistémas de computadores en los cuales se hallan descargado los datos (favor leer el Descargo de Responsabilidad).</li><li>Toda copia electrónica o impresa de productos publicados utilizando los datos provistos por \"Island Conservation\" debe ser enviada, libre de cargo, a los autores de los datos via correo a: Island Conservation, 100 Shaffer Road, Santa Cruz CA USA 95060 o via correo electrónico a <a href=\"mailto:science@islandconservation.org?Subject=Publication(s)%20using%20DIISE\">science@islandconservation.org</a>.</li></ol>",
	"newsContent": "<b>Version 2012.3</b>: esta base de datos fue actualizada el 5 de Diciembre del 2012.",
	"partners_text": "Las personas, organizaciones y agencias que han ayudado a desarrollar la Base de Datos de Especies Invasoras Island Erradicaciones"
}

var config_byDijitId_es = {
	"searchContentDiv": "Búsqueda",
	"resultsContentDiv": "Resúltado",
	"islandContentDiv": "Detalles de la Isla",
	"geography": "... ubicación geográfica",
	"invasive": "... por especies invasoras",
	"eradication": "... por detalle de erradicación",
	"searchButton": "Correr búsqueda", 
	"clearButton": "Limpiar búsqueda",
	"printButton": "Exportar",
	"csvButton": "Exportar",
	"infoDetails": "Isla",
	"infoInvasive": "Erradicación(es)",
	"eradicationDetails": "Los detalles del récord de erradicación",
	"about": "Sobre la Base de Datos de Erradicaciones de Especies Invasoras",
	"news": "Noticias",
	"disclaimer": "Descargo de Responsabilidad",
	"termsOfUse": "Condiciones de uso",
	"errors": "Cómo ayudar",
	"partners": "Socios",	
	"Letter": "Carta",
	"searchTool_tooltip": "Pulse para abrir/cerrar la ventana de búsqueda personalizada.",
	"resultsTool_tooltip": "Pulse para abrir/cerrar la ventana de resultados.",
	"islandsTool_tooltip": "Pulse para abrir/cerrar la ventana de detalles de isla.",
	"csvTool_tooltip": "Pulse para exportar o bajar el archivo .csv de la tabla de resultados.",
	"printTool_tooltip": "Pulse para exportar y bajar el archivo PDF de alta resolución.",
	"basemap_tooltip": "Pulse para cambiar el mapa base.",
	"overview_tooltip": "Pulse para abrir/cerrar la ventana de visión general del mapa.",
	"zoomfull_tooltip": "Pulse para ampliar el mapa a máxima escala.",
	"zoomin_tooltip": "Pulse para ampliar el mapa usando una extensión personalizada.", 
	"splitter_tooltip": "Pulse y arrastre para aumentar o disminuir la tabla visible.",
	"close_tooltip": "Pulse para mostrar u ocultar la tabla.",
	"results_tooltip": "Resúltados de su búsqueda.",
	"island_tooltip": "Información detallada de una isla específica.",
	"r_breeding_tooltip": "Mayús + clic para definiciones completas de Estado Crianza.",
	"experts_tooltip": "Pulse para obtener una lista de expertos que contribuyen y el equipo de recolección de datos TIB.",
	"donate_tooltip": "Pulse para donar hacia el desarrollo TIB a través del sitio Island Conservation Paypal."	
}
