var config_byValues_en = {
	"species_record_tooltip": "Click on a cell to view more details about the record",
	"islands_record_tooltip": "Global Island Database (GID) Code",
	"total_threaten_record_tooltip": "All threatened species on an island",
	"total_invasive_record_tooltip": "All invasive species on an island",
	"eradication_record_tooltip": "Any eradication effort on island from the Database of Island Invasive Species Eradications (DIISE).",
	"breeding_status_tooltip": "Breeding status of the threatened species on the island.",
	"click_for_complete_definitions": "Click for complete definitions.",
	"no_filter": "No search filters chosen.  Please select items from the Search pane to filter by ...",
	"Error selecting the item in the data table": "Error selecting the item in the data table",
	"Download": "Download",
	"Export": "Export",
	"Export Map": "Export Map",
	"Export to CSV": "Export to CSV",	
	"Exporting Map": "Exporting Map",
	"Exporting to CSV": "Exporting to CSV",
	"Download Map": "Download Map",
	"Download CSV": "Download CSV",
	"Processing": "Processing",
	"No thumbnail images found": "No thumbnail images found",
	"Filter": "Filter",
	"Species Details": "Species Details",
	"Location Details": "Location Details",
	"Eradication Details": "Eradication Details",
	"Contact Details": "Contact Details",
	"Common Name": "Common Name",
	"Scientific Name": "Scientific Name",
	"Type (Animal)": "Type (Animal)",
	"Year of Introduction": "Year of Introduction",
	"Latitude": "Latitude",
	"Longitude": "Longitude",
	"Status (Eradication)": "Status (Eradication)",
	"Primary Eradication Method": "Primary Eradication Method",
	"Secondary Eradication Method": "Secondary Eradication Method",
	"Tertiary Eradication Method": "Tertiary Eradication Method",
	"Eradication Start Date": "Eradication Start Date",
	"Eradication End Date": "Eradication End Date",	
	"Primary Baiting Method": "Primary Baiting Method",
	"Secondary Baiting Method": "Secondary Baiting Method",
	"Eradication Method Details": "Eradication Method Details",
	"Trapping Method Details": "Trapping Method Details",
	"Method Description": "Method Description",
	"Primary Toxicant": "Primary Toxicant",
	"Secondary Toxicant": "Secondary Toxicant",
	"Cost": "Cost",
	"Eradication Contact": "Eradication Contact",
	"Contact Email": "Contact Email",
	"Contact Organization": "Contact Organization",
	"Organization Website": "Organization Website",
	"Island Code": "Island Code",
	"Island Name": "Island Name",
	"Name": "Name",
	"Coordinates": "Coordinates",
	"Region": "Region",
	"Country": "Country",
	"Archipelago": "Archipelago",
	"Area (sq km)": "Area (sq km)",	
	"Human Population": "Human Population",
	"Invasive Species": "Invasive Species",
	"Threatened Species": "Threatened Species",
	"Threatened": "Threatened",
	"eradication": "eradication",
	"eradications": "eradications",
	"search in the DIISE": "search in the DIISE",
	"None": "None",
	"none": "none",
	"yes": "yes",
	"no": "no",	
	"Populations": "Populations",
	"populations": "populations",
	"population": "population",
	"no common name": "no common name",
	"unknown": "unknown",
	"Status": "Status",
	"Year": "Year",
	" -- all -- ": " -- all -- ",
	"Arctic Ocean - North Canada": "Arctic Ocean - North Canada",
	"Antarctic Ocean - Peninsula": "Antarctic Ocean - Peninsula",
	"Atlantic Ocean - North": "Atlantic Ocean - North",
	"Atlantic Ocean - South": "Atlantic Ocean - South",
	"Baltic sea": "Baltic sea",
	"Caribbean": "Caribbean",
	"Indian Ocean - East": "Indian Ocean - East",
	"Indian Ocean - West": "Indian Ocean - West",
	"Mediterranean": "Mediterranean",
	"Nusantarian Sea": "Nusantarian Sea",
	"Pacific Ocean - North East": "Pacific Ocean - North East",
	"Pacific Ocean - North West": "Pacific Ocean - North West",
	"Pacific Ocean - South East": "Pacific Ocean - South East",
	"Pacific Ocean - South West": "Pacific Ocean - South West",
	"Persian Gulf": "Persian Gulf",
	"Albania": "Albania",
	"American Samoa": "American Samoa",
	"Anguilla": "Anguilla",
	"Antarctica": "Antarctica",
	"Antigua & Barbuda": "Antigua & Barbuda",
	"Argentina": "Argentina",
	"Aruba": "Aruba",
	"Australia": "Australia",
	"Bahrain": "Bahrain",
	"Barbados": "Barbados",
	"Bermuda": "Bermuda",
	"Bouvet I.": "Bouvet I.",
	"Brazil": "Brazil",
	"British Virgin Is.": "British Virgin Is.",
	"Cambodia": "Cambodia",
	"Canada": "Canada",
	"Cape Verde": "Cape Verde",
	"Cayman Is.": "Cayman Is.",
	"Chile": "Chile",
	"China": "China",
	"Christmas I.": "Christmas I.",
	"Colombia": "Colombia",
	"Comoros": "Comoros",
	"Cook Is.": "Cook Is.",
	"Cuba": "Cuba",
	"Cyprus": "Cyprus",
	"Dominican Republic": "Dominican Republic",
	"Ecuador": "Ecuador",
	"Equatorial Guinea": "Equatorial Guinea",
	"Falkland Is.": "Falkland Is.",
	"Fiji": "Fiji",
	"France": "France",
	"French Polynesia": "French Polynesia",
	"French Southern & Antarctic Lands": "French Southern & Antarctic Lands",
	"Glorioso Is.": "Glorioso Is.",
	"Greece": "Greece",
	"Grenada": "Grenada",
	"Guadeloupe": "Guadeloupe",
	"Guam": "Guam",
	"Haiti": "Haiti",
	"Heard I. & McDonald Is.": "Heard I. & McDonald Is.",
	"Honduras": "Honduras",
	"India": "India",
	"Indonesia": "Indonesia",
	"Iran": "Iran",
	"Italy": "Italy",
	"Jamaica": "Jamaica",
	"Japan": "Japan",
	"Kiribati": "Kiribati",
	"Kuwait": "Kuwait",
	"Madagascar": "Madagascar",
	"Malaysia": "Malaysia",
	"Malta": "Malta",
	"Marshall Is.": "Marshall Is.",
	"Martinique": "Martinique",
	"Mauritius": "Mauritius",
	"Mayotte": "Mayotte",
	"Mexico": "Mexico",
	"Micronesia": "Micronesia",
	"Montserrat": "Montserrat",
	"Morocco": "Morocco",
	"Namibia": "Namibia",
	"Netherlands Antilles": "Netherlands Antilles",
	"New Caledonia": "New Caledonia",
	"New Zealand": "New Zealand",
	"Niue": "Niue",
	"Norfolk I.": "Norfolk I.",
	"North Korea": "North Korea",
	"Northern Mariana Is.": "Northern Mariana Is.",
	"Oman": "Oman",
	"Palau": "Palau",
	"Papua New Guinea": "Papua New Guinea",
	"Peru": "Peru",
	"Philippines": "Philippines",
	"Pitcairn Is.": "Pitcairn Is.",
	"Portugal": "Portugal",
	"Puerto Rico": "Puerto Rico",
	"Qatar": "Qatar",
	"Russia": "Russia",
	"Saint Bartholemy": "Saint Bartholemy",
	"Saint Martin": "Saint Martin",
	"Samoa": "Samoa",
	"Sao Tome & Principe": "Sao Tome & Principe",
	"Saudi Arabia": "Saudi Arabia",
	"Seychelles": "Seychelles",
	"Singapore": "Singapore",
	"Solomon Is.": "Solomon Is.",
	"South Africa": "South Africa",
	"South Georgia & the South Sandwich Is.": "South Georgia & the South Sandwich Is.",
	"South Korea": "South Korea",
	"Spain": "Spain",
	"Sri Lanka": "Sri Lanka",
	"St. Helena": "St. Helena",
	"St. Kitts & Nevis": "St. Kitts & Nevis",
	"St. Lucia": "St. Lucia",
	"St. Pierre and Miquelon": "St. Pierre and Miquelon",
	"St. Vincent & the Grenadines": "St. Vincent & the Grenadines",
	"Taiwan": "Taiwan",
	"Tanzania": "Tanzania",
	"Thailand": "Thailand",
	"The Bahamas": "The Bahamas",
	"Timor-Leste": "Timor-Leste",
	"Tokelau": "Tokelau",
	"Tonga": "Tonga",
	"Trinidad & Tobago": "Trinidad & Tobago",
	"Turkey": "Turkey",
	"Turks & Caicos Is.": "Turks & Caicos Is.",
	"Tuvalu": "Tuvalu",
	"United Arab Emirates": "United Arab Emirates",
	"United States": "United States",
	"United States Minor Outlying Is.": "United States Minor Outlying Is.",
	"Vanuatu": "Vanuatu",
	"Venezuela": "Venezuela",
	"Vietnam": "Vietnam",
	"Virgin Is.": "Virgin Is.",
	"Wallis & Futuna": "Wallis & Futuna",
	"Yemen": "Yemen",
	"Rodent": "Rodent",
	"Ungulate": "Ungulate",
	"Cat": "Cat",
	"Rabbit and Hare": "Rabbit and Hare",
	"Mongoose and Weasel": "Mongoose and Weasel",
	"Dog and Fox": "Dog and Fox",
	"Mammal (Other)": "Mammal (Other)",
	"Reptile": "Reptile",
	"Bird": "Bird",
	"Bird - All": "Bird - All",
	"Bird - Seabird": "Bird - Seabird",
	"Bird - Landbird": "Bird - Landbird",
	"Being Confirmed": "Being Confirmed",
	"In Progress": "In Progress",
	"Incomplete": "Incomplete",
	"Failed": "Failed",
	"Planned": "Planned",
	"Successful": "Successful",
	"Successful (reinvaded)": "Successful (reinvaded)",
	"Unknown": "Unknown",
	"Incursion": "Incursion",
	"Research or Trial": "Research or Trial",
	"Disease": "Disease",
	"Hunting": "Hunting ",
	"Trapping": "Trapping",
	"Toxicant": "Toxicant",
	"Unknown": "Unknown",
	"Other": "Other",
	"Critically Endangered": "Critically Endangered",
	"Endangered": "Endangered",
	"Extinct": "Extinct",
	"Extinct in the Wild": "Extinct in the Wild",
	"Least Concern": "Least Concern",
	"Not Threatened": "Not Threatened",
	"Vulnerable": "Vulnerable",
	"(Present) Species is confirmed to breed on the island": "(Present) Species is confirmed to breed on the island",
	"(Present) Breeding is not confirmed but is suspected based on a number of factors or evidence": "(Present) Breeding is not confirmed but is suspected based on a number of factors or evidence",
	"(Present) Species recorded as past breeder on the island, but current status is unclear": "(Present) Species recorded as past breeder on the island, but current status is unclear",
	"(Present) Breeding status not updated in past 20 years OR not enough data to extrapolate exact breeding island location": "(Present) Breeding status not updated in past 20 years OR not enough data to extrapolate exact breeding island location",
	"(Present) Confirmed extirpated from the island": "(Present) Confirmed extirpated from the island",
	"(Present) Currently listed as EX or EW by IUCN": "(Present) Currently listed as EX or EW by IUCN",
	"(Present) Species introduced to an island outside of its native range or archipelago": "(Present) Species introduced to an island outside of its native range or archipelago",
	"(Historic) Species is confirmed to have bred on the island": "(Historic) Species is confirmed to have bred on the island",
	"(Historic) Breeding is not confirmed but is suspected based on a number of factors or evidence": "(Historic) Breeding is not confirmed but is suspected based on a number of factors or evidence",
	"(Historic) Breeding status is unclear (inconclusive surveys or data)": "(Historic) Breeding status is unclear (inconclusive surveys or data)",
	"(Historic) No record or history of species on island in past 21 ñ 200 years": "(Historic) No record or history of species on island in past 21 ñ 200 years",
	"(Historic) Species is listed as Confirmed for Present Breeding Status": "(Historic) Species is listed as Confirmed for Present Breeding Status",
	"(Historic) Species was introduced to an island outside of its native range or archipelago": "(Historic) Species was introduced to an island outside of its native range or archipelago",
	"Present Breeding": "Present Breeding",
	"Historic Breeding": "Historic Breeding",
	"Potential Breeding": "Potential Breeding",
	"Confirmed": "Confirmed",
	"Data Deficient": "Data Deficient",
	"Extinct": "Extinct",
	"Extirpated": "Extirpated",
	"Introduced": "Introduced",
	"Potential": "Potential",
	"Probable": "Probable",
	"... islands with threatened species": "... islands with threatened species",
	"... islands with invasive species": "... islands with invasive species",
	"species": "species"
}

var config_byId_en = {
	"link_about": "About",
	"link_news": "News",
	"link_disclaimer": "Disclaimer",
	"link_species": "Species",
	"link_terms": "Terms of Use",
	"link_help": "How to Help",
	"link_partners": "Partners",
	"link_contact": "Contact",
	"link_more": "More Info",
	"link_language": "Language",
	"app_language_text": "Language:",
	"language_english_text": "English",
	"language_spanish_text": "Spanish",
	"splash_language_text": "Language:",
	"splash_language_english": "English",
	"splash_language_spanish": "Spanish",
	"cisr": "built by the <a target=\"_blank\" href=\"http://spatial.cisr.ucsc.edu\">center for integrated spatial research (cisr)</a> @ <a target=\"_blank\" href=\"http://www.ucsc.edu\">ucsc</a>",
	"graphicText": "Graphic:",
	"rectangle": "... by Rectangle",
	"polygon":  "... by Polygon",
	"basemap_basic": "Basic",
	"basemap_satellite": "Satellite",
	"basemap_topographic": "Topographic",
	"printOptionsTextNode": "Export Map",
	"printButton": "Export",
	"csvOptionsTextNode": "Export to CSV",
	"csvButton": "Export",
	"regionSelect_label": "Region:",
	"countrySelect_label": "Country:",
	"islandSelect_label": "Island:",
	"threatenedTypeSelect_label": "Type:",
	"threatenedOrderSelect_label": "Order:",
	"threatenedFamilySelect_label": "Family:",
	"threatenedScientificSelect_label": "Scientific Name:",
	"threatenedCommonSelect_label": "Common Name:",	
	"threatenedStatusSelect_label": "Red List Status:",
	"thr_sci_label": "Scientific Name",
	"thr_com_label": "Common Name",
	"invasiveTypeSelect_label": "Type:",
	"invasiveScientificSelect_label": "Scientific Name:",
	"invasiveCommonSelect_label": "Common Name:",
	"inv_sci_label": "Scientific Name",
	"inv_com_label": "Common Name",
	"csvTermsCheck_label": "I agree to the conditions outlined in the Terms of Use above.",
	"printTermsCheck_label": "I agree to the conditions outlined in the Terms of Use above.",
	"queryDefinition": "Filter:",
	"r_islands_text": "Number of islands",
	"r_threats_text": "Number of species",
	"threats_sum_text": "populations",
	"r_type_animal_threat_text": "Type",
	"r_status_breeding_text": "Status (Present Breeding)",
	"invasives_sum_text": "populations",
	"r_invasives_text": "Number of species",
	"r_type_animal_invasives_text": "Type",
	"r_status_invasive_text": "Status (Invasive)",
	"islandTitle": "No Island Selected",
	"table_header_text": "Table",
	"noThumbnails": "No thumbnail images found",
	"aboutContent": '<span class="aboutHeader">Islands are...</span><div style="text-align:center;"><img src="images/land_graph.png" style="margin:0px 20px 0px 0px;"><img src="images/threat_graph.png" style="margin:0px 0px 0px 20px;"></div><br/><span class="aboutHeader">A special conservation need.</span> Islands represent less than 5% of the earth\'s land area yet harbor 80% of known species extinctions since 1500 (Ricketts et al. 2005), and 39% of today\'s IUCN Critically Endangered species (TIB Partners 2012). Invasive vertebrates are a leading cause of insular extinctions and remain a critical threat to endangered island species today (MEA 2005).<br/><br/><span class="aboutHeader">A special conservation opportunity.</span> Proven techniques to protect island biodiversity exist, including more than 1,000 successful island eradications of invasive vertebrates worldwide, often followed by remarkable recoveries of endangered species and ecosystems (Keitt et al. 2011). The challenge now is to increase the scale and application of these proven restoration tools to reverse this tide of island extinctions.<br/><br/><span class="aboutHeader">Prioritizing conservation for threatened island biodiversity.</span> The Threatened Island Biodiversity database is the most comprehensive global review of IUCN Threatened Species breeding on islands and at risk from invasive vertebrates. Our goal is to help guide where conservation intervention can prevent island extinctions. To date the TIB database includes almost 2000 islands for 1300 threatened species, collated from 1800 scientific literature sources and the contribution of more then <span id="experts" onclick="contributors.show();" onmouseover="dojo.style(this.id, {\'color\':\'#D9310B\'});" onmouseout="dojo.style(this.id, {\'color\':\'#000\'});">500 experts</span>.<br/><br/>TIB partners include Island Conservation, University of California at Santa Cruz, Coastal Conservation Action Laboratory, BirdLife International, and the IUCN Invasive Species Specialist Group. Our recommended citation for the TIB database is:',
	"aboutReferenceHeader": "References",
	"aboutFunding": "The online Threatened Island Biodiversity database was built with the support of The David and Lucille Packard Foundation, the National Fish and Wildlife Foundation, and the Global Environment Facility.",
	"errorContent": 'Please help us to maintain the most accurate and up-to-date database of insular threatened species at risk from invasive vertebrates.<br/><br/>Island Conservation, University of California at Santa Cruz, Coastal Conservation Action Laboratory (UCSC CCAL), BirdLife International and IUCN ISSG endeavors to maintain accurate and up-to-date data at all times. However, if errors or omissions are identified, the user should notify <a href="mailto:tib@islandconservation.org">tib@islandconservation.org</a> so that these can be corrected in future releases of the data.',
	"disclaimerContent": "Island Conservation, University of California at Santa Cruz, Coastal Conservation Action Laboratory (UCSC CCAL), BirdLife International and IUCN ISSG makes no warranties or representations, express or implied, regarding the use of the material appearing in this dataset with regard to their correctness, reliability, accuracy, or otherwise. The material and geographic designations in this dataset do not imply the expressions of any opinion whatsoever on the part of Island Conservation, UCSC CCAL, BirdLife International or IUCN ISSG concerning the legal status of any country, territory or area, nor concerning the delimitation of its frontiers or boundaries. None of Island Conservation, UCSC CCAL, BirdLife International or IUCN ISSG nor any affiliated or related entities or content providers shall be responsible or liable to any person, firm or corporation for any loss, damage, injury, claim or liability of any kind or character based on or resulting from any information contained in the dataset. Island Conservation, UCSC CCAL, BirdLife International and IUCN ISSG may update or make changes to the data provided at any time without notice; but no commitment is made to update the information contained therein.",
	"speciesContent":'The species in the Threatened Island Biodiversity Database represent the terrestrial vertebrate species that breed on islands and appear on the IUCN Red List as either Critically Endangered or  Endangered.  Seabird species listed as Vulnerable are also included.<p>Please note this public website does not display all distribution data. In consultation with species experts and IUCN Species Specialist Groups, sensitive distribution data for select species are not displayed on this public website.</p><p>For more information about excluded species from this web portal, you can email us at <a href="mailto:tib@islandconservation.org?Subject=Species%20excluded%20from%20TIB">tib@islandconservation.org</a>.</p>',
	"termsOfUseContent": '<ol><li>The data are supplied only for conservation purposes, scientific analysis or research.</li><li>The recipient of the data will provide a full and appropriate acknowledgement and citation in any materials or publications derived in part or in whole from the data; relevant citation details will be provided with each dataset. For any publications making substantial use of the data, Island Conservation, University of California at Santa Cruz, Coastal Conservation Action Laboratory (UCSC CCAL), BirdLife International and IUCN Invasive Species Specialist Group (ISSG) welcome the opportunity for co-authorship, collaboration and to comment prior to publication. Expressions of interest can be sent to <a href="mailto:tib@islandconservation.org?Subject=Publication(s)%20using%20TIB">tib@islandconservation.org</a>.</li><li>Reproduction of the dataset or products derived from it, either whole or in part, for commercial purposes is prohibited without prior written permission from a representative of Island Conservation, UCSC CCAL, BirdLife International or IUCN ISSG. For the purposes of these Terms of Use, "commercial purposes"ù means a) any use by, on behalf of, or to inform or assist the activities of, a commercial entity (an entity that operates "for profit") or b) use by any non-profit entity for the purposes of revenue generation. If you require permission please contact <a href="mailto:tib@islandconservation.org?Subject=Commercial%20use%20of%20TIB">tib@islandconservation.org</a>.</li><li>The recipient will not publish the data in their original format, either whole or in part, on a website, FTP site, CD, memory stick or any other media. The recipient should provide a link to the original data source location at www.tib.islandconservation.org  where appropriate.</li><li>Use of these data does not constitute endorsement by Island Conservation, UCSC CCAL, BirdLife International or IUCN ISSG of any derived products, reports or analyses. The Island Conservation, University of California, BirdLife International or IUCN ISSG logos must not be used on any derived products, reports or analyses, or supporting materials, without express permission.</li><li>The recipient will only use the data provided for the purpose for which it was requested, if subsequent or different use is required the recipient must contact the Island Conservation, University of California, BirdLife International or IUCN ISSG at <a href="mailto:tib@islandconservation.org?Subject=Modified%20use%20of%20TIB">tib@islandconservation.org</a> again for written approval.</li><li>The recipient will not pass the original datasets on to third parties and will direct all requests for use of the data back to the Island Conservation, University of California, BirdLife International or IUCN ISSG at <a href="mailto:tib@islandconservation.org">tib@islandconservation.org</a>.</li><li>The recipient may only pass on datasets derived from the data supplied by Island Conservation, University of California, BirdLife International or IUCN ISSG if these derived data are supplied with the same terms of use.</li><li>Island Conservation, UCSC CCAL, BirdLife International and IUCN ISSG reserve the right to comment on the accuracy of representation of the data in material produced by a recipient.</li><li>Island Conservation, UCSC CCAL BirdLife International and IUCN ISSG endeavor to maintain accurate and up-to-date data at all times, but can accept no responsibility for the consequences of errors or omissions in the data, for misuse of the data by any organization or individual, or for any damage done to computing systems into which the data are entered (see Disclaimer).</li><li>Either an electronic or two paper copies of all products published using data supplied by Island Conservation, UCSC CCAL, BirdLife International or IUCN ISSG will be sent, free of charge, c/o - Island Conservation, 100 Shaffer Road, Santa Cruz CA USA 95060 or via email to <a href="mailto:tib@islandconservation.org?Subject=Publication(s)%20using%20TIB">tib@islandconservation.org</a>.</li></ol>',
	"newsContent": "<b>Version 2013.1</b>: (March 2013) Database is published online with comprehensive coverage for island breeding IUCN Critically Endangered and Endangered  birds, mammals, amphibians, reptiles plus Vulnerable seabirds.",
	"definitionsContent": '<strong>BIRD &amp; BAT</strong><div class="definitionCategory"><strong><em>Present Breeding Status - Last ~20 years: 1990-Present</em></strong><div class="definition"><span id="bb_present_confirmed_toggle">[+]</span><span class="definitionName" id="bb_present_confirmed" onclick="toggleDefinition(this.id)">Confirmed</span><div class="definitionSub" id="bb_present_confirmed_sub">Definition: Leading expert or literature CONFIRMs breeding and/or species is a single-island endemic<em>Birds</em>: breeding adult pairs, active nests, live/dead fledglings, eggs (whole or fragments), adults flying into crevices/vegetation/burrows with food or nesting materials; female with egg in oviduct (caught in mist nets or with other survey tools); singing/calling male, bird (or) pair holding territory.<br/><br/><em>Bats</em>: "colony" described, mating recorded, observations of "baby" bats or preflight young, records of capture of subadults, records of females tending young; records of mating displays in bat roosts; breeding specimens collected; records of capture of pregnant or lactating females</div><br/><span id="bb_present_probable_toggle">[+]</span><span class="definitionName" id="bb_present_probable" onclick="toggleDefinition(this.id)">Probable</span><div class="definitionSub" id="bb_present_probable_sub">Definition: Breeding not "??Confirmed" but is suspected based on a number of factors and evidence (include in notes) including:</p><p><em>Birds</em>: breeding adults found in mist-nets (females without egg in oviduct), brood patches, "??breeding adult fall outs", radar surveys, spot-light surveys, acoustic monitoring, guano scents, bones of young; Specimens or bones collected that led collector to believe breeding had occurred ; used/abandoned nests.</p><p><em>Bats</em>:, "probable colony" recorded; breeding island mentioned in paper; species is endemic to the region; species is non-migratory </p>1) Island Residents - if no other information but "??resident" is found in the resources or if the word "?resident" was not used but the species "??population"?? is described in the literature. <br />2) Region Endemic - Species is endemic to the region, specific island has been identified and information on the species is available from the past 20 years but no breeding evidence is found in the literature. <br />3) No/unclear breeding information found and species has not been surveyed/observed on island in last 20 yrs  BUT an expert confirms/suspects the species is still there.</div><br/><span id="bb_present_potential_toggle">[+]</span><span class="definitionName" id="bb_present_potential" onclick="toggleDefinition(this.id)">Potential</span><div class="definitionSub" id="bb_present_potential_sub">Definition: Island with Species X in one of the historic breeding categories, but current status is unclear. <br/>1) Potentially "Extirpated"  <ul><li>Most recent survey/island visit(s) yielded no evidence of breeding and it is unclear if species is extirpated. </li><li>Species is definitely absent from the island but the past history is "potential breeding" and NOT "confirmed" or "probable".</li>  </ul>2) If species X varies inter-annually (changes island but stays in same island group from year to year) and was not found on the island during most recent survey<br />3) Island/species has not been surveyed within the last 20 years or unclear if it has been surveyed in the last 20 years<br />4) Observation/survey inconclusive or information about breeding contradicting<ul><li>Example: adults observed but researcher inferred they were from somewhere else; species in a mixed colony and unclear from research which species was actually present; no breeding observed but researcher inferred it was too early for breeding, etc.</li></ul>5) No/inconclusive survey but "suitable breeding habitat"?? recorded by researcher with expertise of the species and who has confirmed other breeding islands.<br />6) At-sea survey recorded breeders near a specific island<br />7) Observations of non-breeders on islands with past breeding<br />8) Recent surveys may have occurred but expert opinion unclear and they have not published or shared related data.<br />9) Specimens collected in last 20 years but breeding not recorded or determined</div><br/><span id="bb_present_deficient_toggle">[+]</span><span class="definitionName" id="bb_present_deficient" onclick="toggleDefinition(this.id)">Data Deficient</span><div class="definitionSub" id="bb_present_deficient_sub">Definition: Island with Species X recorded as "Data Deficient" or "Potential Breeding" for historic breeding status and status has not been updated in the last 20 years.<br/>  1) Not enough data to extrapolate exact island location; breeding island not provided in data or in communications with experts. </br>  2) Data from the last 20 years not available<ul><li>Unshared data, unpublished reports that you can\'t access, no response from experts; have not been able to find any information on surveys or records; etc.</li><li>If an expert suspects breeding but the data is unclear or is contradicting with other data.  </li></ul></div><br/><span id="bb_present_extirpated_toggle">[+]</span><span class="definitionName" id="bb_present_extirpated" onclick="toggleDefinition(this.id)">Extirpated</span><div class="definitionSub" id="bb_present_extirpated_sub">Definition: Confirmed extirpation from the island. Record "extirpated"ù in notes and any information about when it was last observed/surveyed.<br/>** Must be Confirmed or Probable breeding in the past**</div><br/><span id="bb_present_extinct_toggle">[+]</span><span class="definitionName" id="bb_present_extinct" onclick="toggleDefinition(this.id)">Extinct</span><div class="definitionSub" id="bb_present_extinct_sub">Definition: Currently listed as Extinct or Extinct in the Wild by IUCN, but bred on the island prior to its extinction (do not use if species exists somewhere in the wild)</div></div><br/><strong><em>Historic Breeding Status - Last 21-200 years: &lt;1990</em></strong><div class="definition"><span id="bb_historic_confirmed_toggle">[+]</span><span class="definitionName" id="bb_historic_confirmed" onclick="toggleDefinition(this.id)">Confirmed</span><div class="definitionSub" id="bb_historic_confirmed_sub">Definition: Same criteria and notes as for present breeding status but used ONLY if the species is NOT CONFIRMED in the present.  If species is confirmed in the present, use NA as a status in the past</div><br/><span id="bb_historic_probable_toggle">[+]</span><span class="definitionName" id="bb_historic_probable" onclick="toggleDefinition(this.id)">Probable</span><div class="definitionSub" id="bb_historic_probable_sub">Definition: Same criteria and notes as for present breeding status but used ONLY if the species is NOT CONFIRMED in the present.  If species is confirmed in the present, use NA as a status in the past</div><br/><span id="bb_historic_potential_toggle">[+]</span><span class="definitionName" id="bb_historic_potential" onclick="toggleDefinition(this.id)">Potential</span><div class="definitionSub" id="bb_historic_potential_sub">Definition: Same criteria and notes as for present breeding status but used ONLY if the species is NOT CONFIRMED in the present.  If species is confirmed in the present, use NA as a status in the past<br /> 1) Extra criteria/notes<ul>  <li>If an expert or publication confirms past breeding but the record/account of evidence type or year of record is still unclear.</li><li>Specimens collected in past years but breeding evidence not recorded or determined.</li><li>Expert or literature confirms the species was observed on the island &gt;1990 but breeding was never described (and it was NOT a single-island endemic)</li></ul></div><br/><span id="bb_historic_deficient_toggle">[+]</span><span class="definitionName" id="bb_historic_deficient" onclick="toggleDefinition(this.id)">Data Deficient</span><div class="definitionSub" id="bb_historic_deficient_sub">Definition: Same criteria and notes as for present breeding status but used ONLY if the species is NOT CONFIRMED in the present.  If species is confirmed in the present, use NA as a status in the past<br />1) Extra criteria/notes<ul>  <li>Breeding data from last 21-200 years not available/unclear</li>  <li>Unshared data, unpublished reports that you can\'t access, no response from experts or information supplied unclear/contradicting; have not been able to find any information on surveys or records</li></ul></div><br/><span id="bb_historic_na_toggle">[+]</span><span class="definitionName" id="bb_historic_na" onclick="toggleDefinition(this.id)">Not Applicable (NA)</span><div class="definitionSub" id="bb_historic_na_sub">1) Species listed as "CONFIRMED" for Present Breeding Status<br />2) Species translocated to current island but with no historic status there</div></div></div><br/><strong>MAMMAL, REPTILE, AMPHIBIAN</strong><div class="definitionCategory"><em><strong>Present Breeding Status - Last ~20 years: 1990-Present</strong></em><div class="definition"><span id="mr_present_confirmed_toggle">[+]</span><span class="definitionName" id="mr_present_confirmed" onclick="toggleDefinition(this.id)">Confirmed</span><div class="definitionSub" id="mr_present_confirmed_sub">Definition: Leading expert or literature CONFIRMs breeding and/or species is a single-island endemic</p>1) Species observed, recorded, surveyed; collected (including remains) in last 20 years.<br/>2) Species is reported in a publication within the last 20 years or experts confirm current breeding but no record or survey year is available (only used if other choices not available or found)</div><br/><span id="mr_present_probable_toggle">[+]</span><span class="definitionName" id="mr_present_probable" onclick="toggleDefinition(this.id)">Probable</span><div class="definitionSub" id="mr_present_probable_sub">Definition: Breeding not "Confirmed"ù but is suspected based on a number of factors and evidence (include in notes) including:<br/>1) Island Residents - if no other information but "resident" is found in the resources or if the word "resident" was not used but the species "population" is described in the literature. <br />2) Region Endemic -? Species is endemic to the region, specific island has been identified and information on the species is available from the past 20 years but no breeding evidence is found in the literature. <br />3) No/unclear breeding information found and species has not been surveyed/observed on island in last 20 yrs BUT an expert confirms/suspects the species is still there.</div><br/><span id="mr_present_potential_toggle">[+]</span><span class="definitionName" id="mr_present_potential" onclick="toggleDefinition(this.id)">Potential</span><div class="definitionSub" id="mr_present_potential_sub">Definition: Island with Species X in one of the historic breeding categories, but current status is unclear.<br/>1)Potentially "Extirpated"<ul><li>Most recent survey/island visit(s) yielded no evidence of breeding and it is unclear if species is extirpated. </li><li>Species is definitely absent from the island but the past history is "potential breeding"ù and NOT "confirmed"ù or "probable". </li></ul>2) Inconclusive/conflicting surveys, searches, or data<br/>3) Suitable breeding habitat recorded by researcher with expertise of the species and who has confirmed other breeding islands<br/>4) Island/species has not been surveyed or observed within the last 20 years<br /><ul><li>Island/species said to be on the island but the status is unclear and only records are over 20 years old</li></ul>5) Bones from species found on island, age unclear<br/>6) Recent surveys may have occurred but expert opinion unclear and they have not published or shared related data.<br/></div><br/><span id="mr_present_deficient_toggle">[+]</span><span class="definitionName" id="mr_present_deficient" onclick="toggleDefinition(this.id)">Data Deficient</span><div class="definitionSub" id="mr_present_deficient_sub">Definition: Island with Species X recorded as "Data Deficient"ù or "Potential Breeding"ù for historic breeding status and status has not been updated in the last 20 years. </p>1) Not enough data to extrapolate exact island location; breeding island not provided in data or in communications with experts.<br/>2) Data from the last 20 years not available; for example:<ul><li>Unshared data, unpublished reports that you can\'t access, no response from experts; have not been able to find any information on surveys or records; etc.</li><li>If an expert suspects breeding but the data is unclear or is contradicting with other data.</li></ul></div><br/><span id="mr_present_extirpated_toggle">[+]</span><span class="definitionName" id="mr_present_extirpated" onclick="toggleDefinition(this.id)">Extirpated</span><div class="definitionSub" id="mr_present_extirpated_sub">Definition: Confirmed extirpation from the island. Record "extirpated" in notes and any information about when it was last observed/surveyed.<br/>** Must be Confirmed or Probable breeding in the past**</div><br/><span id="mr_present_extinct_toggle">[+]</span><span class="definitionName" id="mr_present_extinct" onclick="toggleDefinition(this.id)">Extinct</span><div class="definitionSub" id="mr_present_extinct_sub">Definition: Currently listed as Extinct or Extinct in the Wild by IUCN, but bred on the island prior to its extinction (do not use if species exists somewhere in the wild)</div></div><br/><strong><em>Historic Breeding Status - Last 21-200 years: &lt;1990</em></strong><div class="definition"><span id="mr_historic_confirmed_toggle">[+]</span><span class="definitionName" id="mr_historic_confirmed" onclick="toggleDefinition(this.id)">Confirmed</span><div class="definitionSub" id="mr_historic_confirmed_sub">Definition: Same criteria and notes as for present breeding status but used ONLY if the species is NOT CONFIRMED in the present.  If species is confirmed in the present, use NA as a status in the past</div><br/><span id="mr_historic_probable_toggle">[+]</span><span class="definitionName" id="mr_historic_probable" onclick="toggleDefinition(this.id)">Probable</span><div class="definitionSub" id="mr_historic_probable_sub">Definition: Same criteria and notes as for present breeding status but used ONLY if the species is NOT CONFIRMED in the present.  If species is confirmed in the present, use NA as a status in the past</div><br/><span id="mr_historic_potential_toggle">[+]</span><span class="definitionName" id="mr_historic_potential" onclick="toggleDefinition(this.id)">Potential</span><div class="definitionSub" id="mr_historic_potential_sub">Definition: Same criteria and notes as for present breeding status but used ONLY if the species is NOT CONFIRMED in the present.  If species is confirmed in the present, use NA as a status in the past<br /> 1) Extra criteria/notes<ul><li>If an expert or publication confirms past breeding but the record/account of evidence type or year of record is still unclear.</li><li>Specimens collected in past years but breeding evidence not recorded or determined.</li><li>Expert or literature confirms the species was observed on the island &gt;1990 but breeding was never described (and it was NOT a single-island endemic).</li></ul></div><br/><span id="mr_historic_deficient_toggle">[+]</span><span class="definitionName" id="mr_historic_deficient" onclick="toggleDefinition(this.id)">Data Deficient</span><div class="definitionSub" id="mr_historic_deficient_sub">Definition: Same criteria and notes as for present breeding status but used ONLY if the species is NOT CONFIRMED in the present.  If species is confirmed in the present, use NA as a status in the past<br />1) Extra criteria/notes<ul>  <li>Breeding data from last 21-200 years not available/unclear</li>  <li>Unshared data, unpublished reports that you can\'t access, no response from experts or information supplied unclear/contradicting; have not been able to find any information on surveys or records</li></ul></div><br/><span id="mr_historic_na_toggle">[+]</span><span class="definitionName" id="mr_historic_na" onclick="toggleDefinition(this.id)">Not Applicable (NA)</span><div class="definitionSub" id="mr_historic_na_sub">1) Species listed as "CONFIRMED" for Present Breeding Status<br />2) Species translocated to current island but with no historic status there</div></div></div>'
}

var config_byDijitId_en = {
	"searchContentDiv": "Search",
	"resultsContentDiv": "Results",
	"islandContentDiv": "Island Details",
	"ovContentDiv": "Overview Map",
	"geography": "... by geographic location",
	"threatened": "... by threatened species",
	"invasive": "... by invasive species",
	"searchButton": "Run Search", 
	"clearButton": "Clear Search",
	"printButton": "Export",
	"csvButton": "Export",
	"infoDetails": "Island",
	"infoThreatened": "Threatened",
	"infoInvasive": "Invasive",
	"about": "About the Threatened Island Biodiversity Database",
	"news": "News",
	"disclaimer": "Disclaimer",
	"species": "Species",
	"termsOfUse": "Terms of Use",
	"errors": "How to Help",
	"partners": "Partners",	
	"Letter": "Letter",
	"csvContinueButton": "Continue",
	"printContinueButton": "Continue",
	"splash_language_spanish_tooltip": "Spanish",
	"splash_language_english_tooltip": "English",
	"searchTool_tooltip": "Click to open/close the custom Search window.",
	"resultsTool_tooltip": "Click to open/close the Results window.",
	"islandsTool_tooltip": "Click to open/close the Island Details window.",
	"csvTool_tooltip": "Click to export and download a .csv file of the results table.",
	"printTool_tooltip": "Click to export and download a high-resolution map.",
	"basemap_tooltip": "Click to change the underlying basemap.",
	"overview_tooltip": "Click to open/close the Overview Map window.",
	"zoomfull_tooltip": "Click to zoom out to the full extent of the map.",
	"zoomin_tooltip": "Click to zoom in to the map using a custom drawn extent.", 
	"splitter_tooltip": "Click and drag to increase or decrease the viewable table.",
	"close_tooltip": "Click to hide or show the table.",
	"search_tooltip": "Build a custom search.",
	"results_tooltip": "Results from your custom search.",
	"island_tooltip": "Detailed information on a specific island.",
	"r_breeding_tooltip": "Shift + Click for complete definitions of Breeding Status.",
	"experts_tooltip": "Click for a list of contributing experts and the TIB data collection team.",
	"donate_tooltip": "Click to donate towards TIB development via the Island Conservation Paypal site.",
	"r_threatened_on_islands": "... islands with threatened species: 0",
	"r_invasives_on_islands": "... islands with invasive species: 0"	
}

var config_byValues_es = {
	"species_record_tooltip": "Pulse una celda para ver m·s detalles sobre el registro",
	"islands_record_tooltip": "Global Island Database (GID) Code",
	"total_threaten_record_tooltip":"Todas las especies amenazadas de la isla",
	"total_invasive_record_tooltip": "Todas las especies invasoras en la isla",
	"eradication_record_tooltip": "Cualquier esfuerzo de erradicaciÛn de la isla desde la base de datos de Especies Invasoras Isla Erradicaciones (DIISE).",
	"breeding_status_tooltip": "CrÌa estado de las especies amenazadas en la isla.",
	"click_for_complete_definitions": "Haga clic para definiciones completas.",
	"no_filter": "No hay filtros de b˙squeda elegido. Por favor, selecciona los artÌculos en el panel de b˙squeda para filtrar por ...",
	"Error selecting the item in the data table": "Error de seleccionar el elemento de la tabla de datos",
	"Download": "Descargar",
	"Export": "Exportar",
	"Export Map": "Exportar el Mapa",
	"Export to CSV": "Exportar a CSV",	
	"Exporting Map": "Exportar el Mapa",
	"Exporting to CSV": "Exportar a CSV",
	"Download Map": "Descargar el Mapa",
	"Download CSV": "Descargar CSV",
	"Processing": "Procesar",
	"No thumbnail images found": "No se encontraron im·genes 'thumbnail'",
	"Results": "Res˙ltado",
	"islands": "islas",
	"Filter": "Filtro",
	"Graphic": "Grafico",
	"Species Details": "Especies Detalles",
	"Location Details": "Detalles de la ubicaciÛn",
	"Eradication Details": "Detalles de erradicaciÛn",
	"Contact Details": "Datos de contacto",
	"Common Name": "Nombre Com˙n",
	"Scientific Name": "Nombre CientÌfico",
	"Type (Animal)": "Tipo (Animal)",
	"Type": "Tipo",
	"Year of Introduction": "AÒo de IntroducciÛn",
	"Latitude": "Latitud",
	"Longitude": "Longitud",
	"Status (Eradication)": "Estado (ErradicaciÛn)",
	"Primary Eradication Method": "ErradicaciÛn Principal",
	"Secondary Eradication Method": "ErradicaciÛn Secundaria",
	"Tertiary Eradication Method": "ErradicaciÛn Terciario",
	"Eradication Start Date": "Fecha Inicio de ErradicaciÛn ",
	"Eradication End Date": "Fecha Final de ErradicaciÛn",	
	"Primary Baiting Method": "Cebo Primaria",
	"Secondary Baiting Method": "Cebo Secundaria",
	"Eradication Method Details": "ErradicaciÛn MÈtodo Detalles",
	"Trapping Method Details": "MÈtodo de Captura Detalles",
	"Method Description": "MÈtodo DescripciÛn",
	"Primary Toxicant": "TÛxico Primaria",
	"Secondary Toxicant": "TÛxico Secundaria",
	"Cost": "Costo",
	"Eradication Contact": "ErradicaciÛn de Contacto",
	"Contact Email": "Correo ElectrÛnico de Contacto",
	"Contact Organization": "Contacto OrganizaciÛn",
	"Organization Website": "OrganizaciÛn Sitio Web",
	"Island Code": "CÛdigo de Isla",
	"Island Name": "Nombre de Isla",
	"Name": "Nombre",
	"Coordinates": "Coordenadas",
	"Region": "RegiÛn",
	"Country": "PaÌs",
	"Archipelago": "ArchipiÈlago",
	"Area (sq km)": "Area (km2)",	
	"Human Population": "PoblaciÛn Humana",
	"Invasive Species": "Especies invasoras",
	"Threatened Species": "Especies amenazadas",
	"Threatened": "Amenazado",
	"Total Threatened Species": "Total de Especies Amenazadas",
	"Total Invasive Species": "Total de Especies Invasoras",
	"Eradication(s)": "ErradicaciÛn(es)",
	"eradication": "erradicaciÛn",
	"eradications": "erradicaciÛnes",
	"search in the DIISE": "b˙squeda en el DIISE",
	"None": "Ninguno",
	"none": "ninguno",
	"yes": "si",
	"no": "no",	
	"Populations": "PoblaciÛnes",
	"populations": "poblaciÛnes",
	"population": "poblaciÛn",
	"no common name": "sin nombre Com˙n",
	"unknown": "desconocido",
	"Status": "Estado",
	"Status (Present Breeding)": "Estado (Anidamiento Actual)",
	"Status (Invasive)": "Estado (Invasor)",
	"Year": "AÒo",
	"IUCN Status": "Estado de UICN",
	" -- all -- ": " -- todo -- ",
	"Arctic Ocean - North Canada": "Oceano Artico - Canada del Norte",
	"Antarctic Ocean - Peninsula": "OcÈano Ant·rtico - PenÌnsula",
	"Atlantic Ocean - North": "OcÈano Atl·ntico - Norte",
	"Atlantic Ocean - South": "OcÈano Atl·ntico - Sur",
	"Baltic sea": "Mar Baltico",
	"Caribbean": "Caribe",
	"Indian Ocean - East": "OcÈano Indico - Este",
	"Indian Ocean - West": "OcÈano Indico- Oeste",
	"Mediterranean": "Mediterr·neo",
	"Nusantarian Sea": "Mar Nusantario",
	"Pacific Ocean - North East": "OcÈano PacÌfico - Noreste",
	"Pacific Ocean - North West": "OcÈano Pacifico - Noroeste",
	"Pacific Ocean - South East": "OcÈano Pacifico- Sureste",
	"Pacific Ocean - South West": "OcÈano Pacifico - Suroeste",
	"Persian Gulf": "Golfo PÈrsico",
	"Albania": "Albania",
	"American Samoa": "Samoa Americana",
	"Anguilla": "Anguila",
	"Antarctica": "Ant·rtida",
	"Antigua & Barbuda": "Antigua y Barbuda",
	"Argentina": "Argentina",
	"Aruba": "Aruba",
	"Australia": "Australia",
	"Bahrain": "Bahrein",
	"Barbados": "Barbados",
	"Bermuda": "Bermuda",
	"Bouvet I.": "Isla Bouvet",
	"Brazil": "Brasil",
	"British Virgin Is.": "Islas VÌrgenes Brit·nicas",
	"Cambodia": "Camboya",
	"Canada": "Canad·",
	"Cape Verde": "Cabo Verde",
	"Cayman Is.": "Islas Caim·n",
	"Chile": "Chile",
	"China": "China",
	"Christmas I.": "Islas de Navidad",
	"Colombia": "Colombia",
	"Comoros": "Comoras",
	"Cook Is.": "Islas Cook",
	"Cuba": "Cuba",
	"Cyprus": "Chipre",
	"Dominican Republic": "Rep˙blica Dominicana",
	"Ecuador": "Ecuador",
	"Equatorial Guinea": "Guinea Ecuatorial",
	"Falkland Is.": "Islas Malvinas (Falklands)",
	"Fiji": "Fiji",
	"France": "Francia",
	"French Polynesia": "Polinesia Francesa",
	"French Southern & Antarctic Lands": "Tierras Australes y Ant·rticas Francesas",
	"Glorioso Is.": "Isla Glorioso",
	"Greece": "Grecia",
	"Grenada": "Granada",
	"Guadeloupe": "Guadalupe",
	"Guam": "Guam",
	"Haiti": "HaitÌ",
	"Heard I. & McDonald Is.": "Islas de Heard y McDonald",
	"Honduras": "Honduras",
	"India": "India",
	"Indonesia": "Indonesia",
	"Iran": "Ir·n",
	"Italy": "Italia",
	"Jamaica": "Jamaica",
	"Japan": "JapÛn",
	"Kiribati": "Kiribati",
	"Kuwait": "Kuwait",
	"Madagascar": "Madagascar",
	"Malaysia": "Malasia",
	"Malta": "Malta",
	"Marshall Is.": "Islas Marshall",
	"Martinique": "Martinica",
	"Mauritius": "Mauricio",
	"Mayotte": "Mayotte",
	"Mexico": "MÈxico",
	"Micronesia": "Micronesia (Estados Federados de)",
	"Montserrat": "Montserrat",
	"Morocco": "Marruecos",
	"Namibia": "Namibia",
	"Netherlands Antilles": "Antillas Neerlandesas",
	"New Caledonia": "Nueva Caledonia",
	"New Zealand": "Nueva Zelandia",
	"Niue": "Niue",
	"Norfolk I.": "Islas Norfolk",
	"North Korea": "Corea del Norte",
	"Northern Mariana Is.": "Islas Marianas Septentrionales",
	"Oman": "Om·n",
	"Palau": "Palau",
	"Papua New Guinea": "Papua Nueva Guinea",
	"Peru": "Per˙",
	"Philippines": "Filipinas",
	"Pitcairn Is.": "Pitcairn",
	"Portugal": "Portugal",
	"Puerto Rico": "Puerto Rico",
	"Qatar": "Qatar",
	"Russia": "FederaciÛn de Rusia",
	"Saint Bartholemy": "Saint-BarthelÈmy",
	"Saint Martin": "Saint Martin",
	"Samoa": "Samoa",
	"Sao Tome & Principe": "Santo TomÈ y PrÌncipe",
	"Saudi Arabia": "Arabia Saudita",
	"Seychelles": "Seychelles",
	"Singapore": "Singapur",
	"Solomon Is.": "Islas SalomÛn",
	"South Africa": "Sud·frica",
	"South Georgia & the South Sandwich Is.": "Islas Georgia y Sandwich del Sur",
	"South Korea": "Corea del Sur",
	"Spain": "EspaÒa",
	"Sri Lanka": "Sri Lanka",
	"St. Helena": "Santa Elena",
	"St. Kitts & Nevis": "Saint Kitts y Nevis",
	"St. Lucia": "Santa LucÌa",
	"St. Pierre and Miquelon": " Saint Pierre y Miquelon",
	"St. Vincent & the Grenadines": "San Vicente y las Granadinas",
	"Taiwan": "Taiw·n",
	"Tanzania": "TanzanÌa ",
	"Thailand": "Tailandia",
	"The Bahamas": "Bahamas",
	"Timor-Leste": "Timor-Leste",
	"Tokelau": "Togo",
	"Tonga": "Tonga",
	"Trinidad & Tobago": "Trinidad y Tabago",
	"Turkey": "TurquÌa",
	"Turks & Caicos Is.": "Islas Turcas y Caicos",
	"Tuvalu": "Tuvalu",
	"United Arab Emirates": "Emiratos ¡rabes Unidos",
	"United States": "Estados Unidos",
	"United States Minor Outlying Is.": "Islas Ultramarinas Menores de Estados Unidos",
	"Vanuatu": "Vanuatu",
	"Venezuela": "Venezuela",
	"Vietnam": "Viet Nam",
	"Virgin Is.": "Islas VÌrgenes de los Estados Unidos",
	"Wallis & Futuna": "Islas Wallis y Futuna",
	"Yemen": "Yemen",
	"Rodent": "Roedor",
	"Rodent (Rattus)": "Roedor (Rattus)",
	"Rodent (Mus)": "Roedor (Mus)",
	"Ungulate": "Ungulado",
	"Cat": "Gato",
	"Rabbit and Hare": "Conejo y Liebre",
	"Mongoose and Weasel": "Mangosta y Comadreja",
	"Dog and Fox": "Perro y Zorro",
	"Reptile": "Reptil",
	"Reptile (Snake)": "Reptil (Serpiente)",
	"Bird": "Ave",
	"Bird (Raptor)": "Ave (Raptor)",
	"Bird - All": "Ave - Todo",
	"Bird - Seabird": "Ave - Ave marina",
	"Bird - Landbird": "Ave - Ave terrestre",
	"Seabird": "Ave marina",
	"Landbird": "Ave terrestre",
	"Mammal": "MamÌfero",
	"Mammal (Other)": "MamÌfero (otro)",
	"Primate": "Primate",
	"Amphibian": "Amfibio",
	"Reptile (snake)": "Reptil (serpiente)",
	"Bird (raptor)": "Ave (raptor)",
	"Fish": "Pez",
	"Invertebrate": "Invertebrado",
	"Unknown": "Desconocido",
	"Confirmed": "Confirmado",
	"Suspected": "Sospechado",
	"None": "Ninguno",
	"On-going eradication": "ErradicaciÛn en proceso",
	"NA": "NA",
	"Other": "Otro",
	"Critically Endangered": "En Peligro CrÌtico",
	"Endangered": "En Peligro",
	"Extinct": "Extincto",
	"Extinct in the Wild": "Extinto en Estado Silvestre",
	"Least Concern": "PreocupaciÛn Menor",
	"Not Threatened": "Casi Amenazada",
	"Vulnerable": "Vulnerable",
	"(Present) Species is confirmed to breed on the island": "(Presente) Especies que se confirme que crÌan en la isla",
	"(Present) Breeding is not confirmed but is suspected based on a number of factors or evidence": "(Presente) Crianza no est· confirmada pero se sospecha sobre la base de un n˙mero de factores o pruebas",
	"(Present) Species recorded as past breeder on the island, but current status is unclear": "(Presente) Especies registran como criador pasado en la isla, pero la situaciÛn actual no es clara",
	"(Present) Breeding status not updated in past 20 years OR not enough data to extrapolate exact breeding island location": "(Presente) Estado Breeding no se actualiza en los ˙ltimos 20 aÒos o no suficientes datos para extrapolar ubicaciÛn exacta reproducciÛn isla",
	"(Present) Confirmed extirpated from the island": "(Presente) ConfirmÛ extirpada de la isla",
	"(Present) Currently listed as EX or EW by IUCN": "(Presente) Actualmente figura como EX o EW por la UICN",
	"(Present) Species introduced to an island outside of its native range or archipelago": "(Presente) Especies introducidas a una isla fuera de su ·rea de distribuciÛn natural o archipiÈlago",
	"(Historic) Species is confirmed to have bred on the island": "(HistÛrico) Las especies se confirma que se han reproducido en la isla",
	"(Historic) Breeding is not confirmed but is suspected based on a number of factors or evidence": "(HistÛrico) Crianza no est· confirmado, pero se sospecha sobre la base de un n˙mero de factores o pruebas",
	"(Historic) Breeding status is unclear (inconclusive surveys or data)": "(HistÛrico) De estado de crÌa est· claro (encuestas o datos no concluyentes)",
	"(Historic) No record or history of species on island in past 21 ñ 200 years": "(HistÛrico) No hay ning˙n registro o la historia de las especies en la isla en ˙ltimos 21 - 200 aÒos",
	"(Historic) Species is listed as Confirmed for Present Breeding Status": "(HistÛrico) Especies aparece como Confirmado Presente Estado Crianza",
	"(Historic) Species was introduced to an island outside of its native range or archipelago": "(HistÛrico) Las especies se introdujo en una isla fuera de su ·rea de distribuciÛn natural o archipiÈlago",	
	"Present Breeding": "Anidamiento Actual",
	"Historic Breeding": "Anidamiento Historico",
	"Potential Breeding": "Anidamiento Potencial",
	"Confirmed": "Confirmado",
	"Data Deficient": "Datos Deficientes",
	"Extinct": "Extinto",
	"Extirpated": "Extirpado",
	"Introduced": "Introducido",
	"Potential": "Potencial",
	"Probable": "Probable",
	"... islands with threatened species": "... islas con especies amenazadas",
	"... islands with invasive species": "... islas con especies invasoras",
	"species": "especies"
}

var config_byId_es = {
	"link_about": "Acerca de Nosotros",
	"link_news": "Noticias",
	"link_disclaimer": "Descargo de Responsabilidad",
	"link_species": "Las Especies",
	"link_terms": "TÈrminos de uso",
	"link_help": "CÛmo puedes ayudar",
	"link_partners": "Socios",
	"link_contact": "Cont·ctenos",
	"link_more": "M·s Info",
	"link_language": "Lengua",
	"app_language_text": "Lengua:",
	"language_english_text": "InglÈs",
	"language_spanish_text": "EspaÒol",
	"splash_language_text": "Lengua:",
	"splash_language_english": "InglÈs",
	"splash_language_spanish": "EspaÒol",
	"cisr": "construido por el <a target=\"_blank\" href=\"http://spatial.cisr.ucsc.edu\">centro para investigaciÛn espacial integrada (cisr)</a> @ <a target=\"_blank\" href=\"http://www.ucsc.edu\">ucsc</a>",
	"graphicText": "Grafico:",
	"rectangle": "... por Rectangulo",
	"polygon":  "... por Poligono",
	"basemap_basic": "B·sico",
	"basemap_satellite": "SatÈlite",
	"basemap_topographic": "Topogr·fico",
	"printOptionsTextNode": "Exportar el Mapa",
	"csvOptionsTextNode": "Exportar a CSV",
	"regionSelect_label": "RegiÛn:",
	"countrySelect_label": "Pais:",
	"islandSelect_label": "Isla:",
	"threatenedTypeSelect_label": "Tipo:",
	"threatenedOrderSelect_label": "Orden:",
	"threatenedFamilySelect_label": "Familia:",
	"threatenedScientificSelect_label": "Nombre CientÌfico:",
	"threatenedCommonSelect_label": "Nombre Com˙n:",	
	"threatenedStatusSelect_label": "Estado de la lista roja de la IUCN:",
	"thr_sci_label": "Nombre CientÌfico",
	"thr_com_label": "Nombre Com˙n",
	"invasiveTypeSelect_label": "Tipo:",
	"invasiveScientificSelect_label": "Nombre CientÌfico:",
	"invasiveCommonSelect_label": "Nombre Com˙n:",
	"inv_sci_label": "Nombre CientÌfico",
	"inv_com_label": "Nombre Com˙n",
	"csvTermsCheck_label": "Estoy de acuerdo con la condiciones que se indican en los tÈrminos y Condiciones de Uso sobre.",
	"printTermsCheck_label": "Estoy de acuerdo con la condiciones que se indican en los tÈrminos y Condiciones de Uso sobre.",	
	"queryDefinition": "Filtro:",
	"r_islands_text": "N˙mero de islas",
	"r_threats_text": "N˙mero de especies",
	"threats_sum_text": "poblaciÛnes",
	"r_type_animal_threat_text": "Tipo",
	"r_status_breeding_text": "Estado (Anidamiento Actual)",
	"invasives_sum_text": "poblaciÛnes",
	"r_invasives_text": "N˙mero de especies",
	"r_type_animal_invasives_text": "Tipo",
	"r_status_invasive_text": "Estado (Invasor)",
	"islandTitle": "Ninguna Isla Seleccionada",
	"table_header_text": "Tabla",
	"noThumbnails": "No se encontraron im·genes 'thumbnail'...",
	"aboutContent": '<span class="aboutHeader">Las islas son...</span><div style="text-align:center;"><img src="images/land_graph.png" style="margin:0px 20px 0px 0px;"><img src="images/threat_graph.png" style="margin:0px 0px 0px 20px;"></div><br/><span class="aboutHeader">Una necesidad especial de conservaciÛn.</span> Las islas representan menos del 5% de la masa terrestre, sin embargo  80% de las extinciones de especies desde 1500 han sido en islas (Ricketts et al., 2005), y 39% de las Especies Amenazadas hoy en dÌa seg˙n la UICN (Colaboradores de TIB, 2012). Los vertebrados invasores son la causa principal de las extinciones insulares y representan a˙n una amenaza crÌtica para la especies amenazadas hoy en dÌa (MEA, 2005).<br/><br/><span class="aboutHeader">Una oportunidad especial de conservaciÛn.</span> Existen tÈcnicas comprobadas para proteger la biodiversidad presente en islas, incluyendo m·s de 1000 erradicaciones exitosas de vertebrados invasores a nivel mundial, usualmente seguidas de descubrimientos significativos de especies amenazadas y ecosistemas (Keitt et al., 2011). El reto ahora es aumentar la escala y aplicaciÛn de estas herramientas de restauraciÛn para revertir la ola de extinciones insulares.<br/><br/><span class="aboutHeader">Priorizar la conservaciÛn de la biodiversidad de especies amenazadas en islas.</span>  La base de datos de Biodiversidad Amenazada en Islas es la revisiÛn global m·s completa de Especies Amenazadas de la UICN que se reproducen en islas y que est·n en riesgo debido a vertebrados invasores. Nuestro objetivo es ayudar a guiar donde intervenciones de conservaciÛn pueden prevenir extinciones en islas. A la fecha, la base de datos TIB incluye casi 2000 islas que albergan 1300 especies amenazadas obtenidas de 1800 fuentes de literatura cientÌfica y con la contribuciÛn de m·s de <span id="experts" onclick="contributors.show();" onmouseover="dojo.style(this.id, {\'color\':\'#D9310B\'});" onmouseout="dojo.style(this.id, {\'color\':\'#000\'});">500 expertos</span>.<br/><br/>Colaboradores de TIB incluyen "Island Conservation", la Universidad de California en Santa Cruz, "Coastal Conservation Action Laboratory", "BirdLife International", y el grupo especialista en especies invasoras de la UICN. Nuestra cita recomendada para la base de datos de TIB es:',
	"aboutReferenceHeader": "BibliografÌa",
	"aboutFunding": "La base de datos de Threatened Island Biodiversity fue creada con el apoyo financiero del David and Lucille Packard Foundation, el National Fish and Wildlife Foundation y el Fondo para el Medio Ambiente Mundial.",
	"errorContent": "\"Island Conservation\" se esfuerza por mantener datos precisos y actuales en todo momento. Sin embargo, de identificarse errores u omisiones, el usuario debe notificar a \"Island Conservation\" <a href=\"mailto:science@islandconservation.org\">science@islandconservation.org</a> para que estos puedan ser corregidos en la base de datos. Por favor marcar cualquier correspondencia con el titulo: \"Base de datos de islas y erradicaciones de especies invasoras\".",
	"disclaimerContent": '"Island Conservation", la Universidad de California en Santa Cruz, "Coastal Conservation Action Laboratory (UCSC CCAL)", "BirdLife International", y la UICN ISSG no establecen garantÌas o representaciones de forma expresa o implicÌta, con relaciÛn a la precisiÛn, confiabilidad, u otros par·metros del material presentado en esta base de datos. El material y las designaciones geogr·ficas en esta base de datos no representan las opiniones de "Island Conservation", UCSC CCAL, "BirdLife International", o UICN ISSG con relaciÛn al estado legal de ning˙n paÌs, territorio o ·rea, ni concerniente a la delimitaciÛn de sus fronteras o lÌmites.  Ni "Island Conservation", UCSC CCAL, "BirdLife International", o UICN ISSG, tampoco ninguna de sus entidades afiliadas o informantes es responsable ante ninguna persona, firma o corporaciÛn por pÈrdida, daÒos y perjuicios de ning˙n tipo basados o como resultado del uso de la informaciÛn contenida en esta base de datos. "Island Conservation", UCSC CCAL, "BirdLife International", y UICN ISSG pueden actualizar o cambiar los datos proporcionados en cualquier momento sin previo aviso; pero no se establece ning˙n compromiso sobre actualizar la informaciÛn aqui contenida.',
	
	"speciesContent":'Las especies encontradas en la base de datos de Biodiversidad Amenazada en Islas representan a aquellas que se reproducen en islas y son clasificadas como las m·s amenazadas (\"Critically Endangered\" o \"Endangered\") en la Lista Roja de la UICN. Aves marinas clasificadas como Vulnerables tambiÈn est·n incluidas.<p>Por favor noten que este sitio web no muestra datos de distribuciÛn para todas las especies. En consulta con expertos y con el grupo de especialistas de especies de la UICN, para varias especies con datos sensibles de distribuciÛn no se muestran en este sitio web p˙blico.</p><p>Para m·s informaciÛn acerca de las especies excluidas de Èste sitio web puede contactarnos a travÈs del correo electrÛnico <a href="mailto:tib@islandconservation.org?Subject=Species%20excluded%20from%20TIB">tib@islandconservation.org</a>.</p>',
	
	"termsOfUseContent": '<ol><li>Los datos son suministrados para fines de conservaciÛn, an·lisis cientÌfico o investigaciÛn exclusivamente.</li><li>El usario de los datos acreditar·, reconocer· por entero y citar· cualquier material o publicaciones derivadas en parte o completamente de los datos; detalles para citas relevantes ser·n proporcionados con cada conjunto de datos. Para cualquier publicaciÛn que haga uso sustancial de los datos, "Island Conservation", Universidad de California Santa Cruz, "Coastal Conservation Action Laboratory (UCSC, CCAL)"," BirdLife International" y la UICN Invasive Species Specialist Group ISSG est·n abiertos a la posibilidad de ser co-autores, colaborar y comentar previo a la publicaciÛn. Expresiones de interÈs pueden ser enviadas a <a href="mailto:tib@islandconservation.org?Subject=Publication(s)%20using%20TIB">tib@islandconservation.org</a>.</li><li>La reproducciÛn de la base de datos o productos derivados de ella, por completo o en parte, para propÛsitos comerciales, est· prohibido sin permiso previo por escrito de un representante de "Island Conservation", UCSC CCAL," Birdlife International", o UICN ISSG. Para propÛsitos de estos TÈrminos de Uso, "propÛsito comercial" significa a) cualquier uso por, en representaciÛn de, o para informar o asistir las actividades de una entidad comercial (una entidad que opera "con fines de lucro") o b) uso por parte de una entidad sin fines de lucro para propÛsitos de generar ingresos. Si requiere permiso por favor contacte <a href="mailto:tib@islandconservation.org?Subject=Commercial%20use%20of%20TIB">tib@islandconservation.org</a>.</li><li>El usuario no publicar· los datos en su formato original, de forma completa ni en partes, en una p·gina de internet, sitio FTP, CD, USB u otros medios. El recipiente debe proporcionar un enlace a la ubicaciÛn original de la fuente de datos de www.tib.islandconservation.org cuando sea apropiado.</li><li>Uso de los datos no constituye la aprobaciÛn por "Island Conservation", UCSC CCAL, "BirdLife International" o UICN ISSG de ninguno de los productos derivados, reportes o an·lisis. Los logotipos de "Island Conservation", Universidad de California, "BirdLife International", o UICN ISSG no deben ser utilizados en ning˙n producto derivado, reporte o an·lisis, o material de apoyo, sin permiso.</li><li>El usuario solo usar· los datos proporcionados para el propÛsito para el cual fueron solicitados, su uso posterior o distinto requiere que el destinatario contacte nuevamente a "Island Conservation", la Universidad de California, BirdLife International o UICN ISSG a travÈs de <a href="mailto:tib@islandconservation.org?Subject=Modified%20use%20of%20TIB">tib@islandconservation.org</a> para recibir aprobaciÛn por escrito.</li><li>El usuario no proporcionar· los datos originales a terceras personas y deber· enviar nuevamente cualquier solicitud de uso a "Island Conservation", la Universidad de California, BirdLife International o UICN ISSG a travÈs de <a href="mailto:tib@islandconservation.org">tib@islandconservation.org</a>.</li><li>El recipiente solo entregar· bases de datos derivadas de los datos suplementados por "Island Conservation", la Universidad de California," BirdLife International", o UICN ISSG si estos son derivados de los datos suplementados bajo los mismos tÈrminos de uso.</li><li>"Island Conservation", la Universidad de California, "BirdLife International" y UICN ISSG se reservan el derecho de comentar sobre la precisiÛn de la representaciÛn de los datos producidos por el destinatario.</li><li>Island Conservation, la Universidad de California, "BirdLife International" y UICN ISSG se esfuerzan por mantener datos precisos y actualizados en todo momento, pero no se hacen responsables de las consecuencias producto de errores y omisiones en los datos, mal uso de los datos por una organizaciÛn o individuo, o por daÒos a sistÈmas de computaciÛn donde se han ingresado los datos (ver Descargo de Responsabilidad).</li><li>Bien sea copias electrÛnicas o impresas de todos los productos publicados usando los datos provistos por "Island Conservation",UCSC CCAL, "BirdLife International" o UICN ISSG deben ser enviados, libre de cargos a Island Conservation, 100 Shaffer Road, Santa Cruz CA USA 95060 o por correo elÈctronico a <a href="mailto:tib@islandconservation.org?Subject=Publication(s)%20using%20TIB">tib@islandconservation.org</a></li></ol>',
	
	"definitionsContent": '<strong>AVES y MURCIELAGOS</strong><div class="definitionCategory"><strong><em>Estado actual de anidamiento - Ultimos ~ 20 aÒos - Presente</em></strong><div class="definition"><span id="bb_present_confirmed_toggle">[+]</span><span class="definitionName" id="bb_present_confirmed" onclick="toggleDefinition(this.id)">Confirmado</span><div class="definitionSub" id="bb_present_confirmed_sub">DefiniciÛn: Consulta con experto o la literatura confirma que el anidamiento y/o la especie es un ave endÈmico de una ˙nica isla.<br/><br/><em>Aves</em>: anidamiento, pares de adultos, nidos activos, crÌas vivas/muertas, huevos (completos o en fragmentos), adultos volando a grietas/vegetaciÛn/huecos con alimento o materiales para construcciÛn de nidos; hembras con huevos en el oviducto (capturadas en redes de neblina o con otras herramientas de monitoreo); macho cantando/llamando, ave (o) pareja defendiendo territorio.<br/><br/><em>MurciÈlagos</em>: "colonia" descrita, apareamiento confirmado, observaciones de murciÈlagos "pichones" o juveniles "pre-vuelo;  records de captura de subadultos; records de hembras atendiendo juveniles; records de comportamiento nupcial en las colonias; colecta de especÌmenes en estado de madurez sexual; records de captura de hembras preÒadas o lactando.</div><br/><span id="bb_present_probable_toggle">[+]</span><span class="definitionName" id="bb_present_probable" onclick="toggleDefinition(this.id)">Probable</span><div class="definitionSub" id="bb_present_probable_sub">DefiniciÛn: ReproducciÛn no "confirmada" pero se sospecha basado en el n˙mero de factores y en evidencia (incluÌda en notas) que incluyen:</p><p><em>Aves</em>: adultos en estado de madurez sexual encontrados en las redes de neblina (hembras sin huevos en el oviducto), parches de crÌa; "caÌda de adultos maduros", monitoreo por radar, monitoreo usando l·mparas, monitoreo ac˙stico, esencia de guano, huesos de juveniles; especÌmenes o huesos colectados que conllevaron al colector a creer que habÌa ocurrido anidamiento; uso/nidos abandonados.</p><p><em>MurciÈlagos</em>: registro de "colonia probable"; isla de reproducciÛn mencionada en artÌculo; especie es endÈmica a la regiÛn; especie es no-migratoria.</p>1) Residentes de islas - si no hay otra informaciÛn pero "residente" se encuentra en los recursos o si la palabra "residente" no fue usada per la poblaciÛn de la especie es descrita en la literatura. <br />2) EndÈmico de la regiÛn - especies es endÈmica de la regiÛn, una isla especÌfica ha sido identificada e informaciÛn sobre la especie est· disponible para los ˙ltimos 20 aÒos pero no hay evidencia de reproducciÛn en la literatura.  <br />3) InformaciÛn no existe o no est· clara y la especie no ha sido observada/monitoreada en la isla en los ˙ltimos 20 aÒos PERO opiniÛn de experto confirma/sospecha que la especie a˙n est· allÌ.</div><br/><span id="bb_present_potential_toggle">[+]</span><span class="definitionName" id="bb_present_potential" onclick="toggleDefinition(this.id)">Potencial</span><div class="definitionSub" id="bb_present_potential_sub">DefiniciÛn: Isla con especie X en una de las categorÌas histÛricas de reproducciÛn, pero su estado no est· claro. <br/>1) "Potencialmente extirpada"<ul><li>Las visitas/monitoreos m·s recientes no arrojaron evidencia de anidamiento y no est· claro si la especie fue extirpada. </li><li>La especie definitivamente est· ausente de la isla pero la historia anterior la establece como "anidamiento potencial" y NO "confirmada" o "probable".</li></ul>2) Si la especie X varia inter-anualmente (cambia de isla pero se mantiene en el mismo grupo de islas de aÒo a aÒo) y no fue encontrada en la isla durante el  monitoreo m·s reciente<br />3) Isla/especie no ha sido monitoreada en los ˙ltimos 20 aÒos o no est· claro si ha sido evaluada en los ˙ltimos 20 aÒos<br />4) ObservaciÛn/monitoreo inconcluso o informaciÛn sobre anidamiento contradictoria<ul><li>Ejemplo: adultos observados pero el investigador infiriÛ que eran de otro lugar; especies en una colonia mixta y no fue claro en la investigaciÛn si la especie evidentemente estaba presente; anidamiento no observado pero el investigador infiriÛ que era muy temprano para eventos reproductivos, etc.</li></ul>5) Monitoreo ausente/inconcluso pero registro por parte del investigador  con experticia en la especie y quien ha confirmado reproducciÛn en otras islas de "habitat adecuado para anidamiento"<br />6) Monitoreo desde el mar registrÛ adultos reproductivos cerca de una isla especÌfica<br />7) Observaciones de individuos no reproductivos en islas con registros pasados de animaiento<br />8) Registros recientes pueden haber ocurrido pero la opiniÛn de expertos no est· clara y no han publicado o compartido los datos.<br />9) EspecÌmenes colectados en los ˙ltimos 20 aÒos pero no se ha determinado o registrado anidamiento </div><br/><span id="bb_present_deficient_toggle">[+]</span><span class="definitionName" id="bb_present_deficient" onclick="toggleDefinition(this.id)">Datos Deficientes</span><div class="definitionSub" id="bb_present_deficient_sub">DefiniciÛn: Isla con especies X fue registrada como "deficiente de datos" o "anidamiento potencial" de un estado histÛrico de anidamiento y no se ha actualizado en los ˙ltimos 20 aÒos<br/>1) No hay suficientes datos para extrapolar la ubicaciÛn exacta de la isla; anidamiento en la isla no fue proporcionado en los datos o en comunicaciones con expertos. </br>2) Datos de los ˙ltimos 20 aÒos no est·n disponibles<ul><li>Datos no compartidos, registros no publicados o que no se pueden accesar, no hay respuesta de expertos; no ha sido posible encontrar ninguna informaciÛn en monitoreos o registros, etc.</li><li>Si un experto sospecha anidamiento pero los datos no son claros o contradictorios</li></ul></div><br/><span id="bb_present_extirpated_toggle">[+]</span><span class="definitionName" id="bb_present_extirpated" onclick="toggleDefinition(this.id)">Extirpado</span><div class="definitionSub" id="bb_present_extirpated_sub">DefiniciÛn: extirpaciÛn confirmada de la isla. Registro de "extirpada" en notas y cualquier informaciÛn sobre cuando fue observada/monitoreada la ˙ltima vez<br/>** Debe ser confirmada o anidamiento posible en el pasado **</div><br/><span id="bb_present_extinct_toggle">[+]</span><span class="definitionName" id="bb_present_extinct" onclick="toggleDefinition(this.id)">Extinta</span><div class="definitionSub" id="bb_present_extinct_sub">DefiniciÛn: Actualmente listada como Extinta o Extinta en Vida Silvestre por la UICN, pero se reprodujo antes de su extinciÛn en la isla (no usar si la especie existe en vida sivestre en otro lugar)</div></div><br/><strong><em>Estado historico de anidamiento - ultimos 21-200 aÒos : &lt;1990</em></strong><div class="definition"><span id="bb_historic_confirmed_toggle">[+]</span><span class="definitionName" id="bb_historic_confirmed" onclick="toggleDefinition(this.id)">Confirmado</span><div class="definitionSub" id="bb_historic_confirmed_sub">DefiniciÛn: Mismo criterio y notas que para estado de reproducciÛn actual pero usado SOLO si la especie NO HA SIDO CONFIRMADA en el presente. Si la especie es confirmada en el presente, usar NA como estado en el pasado.</div><br/><span id="bb_historic_probable_toggle">[+]</span><span class="definitionName" id="bb_historic_probable" onclick="toggleDefinition(this.id)">Probable</span><div class="definitionSub" id="bb_historic_probable_sub">DefiniciÛn: Mismo critero y notas que para estado de reproducciÛn actual pero usado SOLO si la especie NO HA SIDO CONFIRMADA en le presente. Si la especie es confirmada en el presente, usar NA como estado en el pasado.</div><br/><span id="bb_historic_potential_toggle">[+]</span><span class="definitionName" id="bb_historic_potential" onclick="toggleDefinition(this.id)">Potencial</span><div class="definitionSub" id="bb_historic_potential_sub">DefiniciÛn: Mismo critero y notas que para estado de reproducciÛn actual pero usado SOLO si la especie NO HA SIDO CONFIRMADA en le presente. Si la especie es confirmada en el presente, usar NA como estado en el pasado<br />1) Criterios extra/notas<ul><li>Si un experto o publicaciÛn confirma anidamiento pasado pero el registro/cuenta de tipo de evidencia o aÒo del record a˙n no est· claro.</li><li>EspecÌmenes colectados en aÒos pasados pero evidencia de anidamiento no ha sido registrada o determinada</li><li>Expertos o literatura confirma que la especies fue observada en la isla > 1990 pero anidamiento nunca ha sido descrito (y NO es un endÈmico de una ˙nica isla)</li></ul></div><br/><span id="bb_historic_deficient_toggle">[+]</span><span class="definitionName" id="bb_historic_deficient" onclick="toggleDefinition(this.id)">Deficiente de datos</span><div class="definitionSub" id="bb_historic_deficient_sub">DefiniciÛn: Mismo critero y notas que para estado de reproducciÛn actual pero usado SOLO si la especie NO HA SIDO CONFIRMADA en le presente. Si la especie es confirmada en el presente, usar NA como estado en el pasado.<br />1) Criterios extra/notas<ul> <li>Datos de anidamiento de los ˙ltimos 21 - 200 aÒos no est·n disponibles/no son claros</li><li>Datos no compartidos, registros no publicados que no se pueden accesar, no hay respuesta de expertos o la informaciÛn suplementada no es clara/contradictoria; no ha sido posible encontrar informaciÛn en monitoreos o registros.</li></ul></div><br/><span id="bb_historic_na_toggle">[+]</span><span class="definitionName" id="bb_historic_na" onclick="toggleDefinition(this.id)">No aplicable (NA)</span><div class="definitionSub" id="bb_historic_na_sub">1) Epecie lsitada como "confirmada" para Estado Reproductivo Actual<br />2) Especie translocada a isla actual pero no hay evidencia historica allÌ</div></div></div><br/><strong>MAMIFERO, REPTIL, ANFIBIO</strong><div class="definitionCategory"><em><strong>Estado reproductivo actual - Ultimos ~ 20 aÒos: 1990 - Presente</strong></em><div class="definition"><span id="mr_present_confirmed_toggle">[+]</span><span class="definitionName" id="mr_present_confirmed" onclick="toggleDefinition(this.id)">Confirmado</span><div class="definitionSub" id="mr_present_confirmed_sub">DefiniciÛn: experto o literatura CONFIRMAN reproducciÛn y/o la especie es endÈmica de una ˙nica isla</p>1) Especie observada, registrada, monitoreada; colectada(incluyendo restos) en lo ˙ltimos 20 aÒos.<br/>2) Especie reportada en una publicaciÛn en los ˙ltimos 20 aÒos o expertos confirman anidamiento actual pero no hay registro o aÒo de monitoreo no est· disponible (usado sÛlo si otras opciones no se encuentran o no est·n disponibles).</div><br/><span id="mr_present_probable_toggle">[+]</span><span class="definitionName" id="mr_present_probable" onclick="toggleDefinition(this.id)">Probable</span><div class="definitionSub" id="mr_present_probable_sub">DefiniciÛn: ReproducciÛn no "confirmada" pero se sospecha basado en el n˙mero de factores y en evidencia (incluÌda en notas) que incluyen:</br>1) Residentes de islas - si no hay otra informaciÛn pero "residente" se encuentra en los registros o si la palabra "residente" no fue usada pero la poblaciÛn de la especie es descrita en la literatura.<br />2) EndÈmico de la regiÛn - especies es endÈmica de la regiÛn, una isla especÌfica ha sido identificada e informaciÛn sobre la especie est· disponible para los ˙ltimos 20 aÒos pero no hay evidencia de reproducciÛn en la literatura. <br />3) InformaciÛn no existe o no est· clara y la especie no ha sido observada/monitoreada en la isla en los ˙ltimos 20 aÒos PERO opiniÛn de experto confirma/sospecha que la especie a˙n est· allÌ.</div><br/><span id="mr_present_potential_toggle">[+]</span><span class="definitionName" id="mr_present_potential" onclick="toggleDefinition(this.id)">Potencial</span><div class="definitionSub" id="mr_present_potential_sub">DefiniciÛn: Isla con especie X en una de las categorÌas histÛricas de reproducciÛn, pero su estado no est· claro.<br/>1) Potencialmente Extirpada<ul><li>Visita/monitoreo m·s reciente a la isla no arrojÛ evidencia de reproducciÛn y no est· claro si la especie fue extirpada.</li><li>Especie definitivamente ausente de la isla pero en la historia hay evidencia de "reproducciÛn potencial" y NO "confirmado" o "probable".</li></ul>2) Evaluaciones inconclusas/conflictivas, b˙squedas o datos<br/>3) Habitat reproductivo adecuado registrado por el investigador con experticia en la especie y quien ha confirmado otras islas de anidamiento<br/>4) Isla/especie no ha sido monitoreada en los ˙ltimos 20 aÒos <br/><ul><li>Isla/especie se ha dicho que est· en la isla pero su estado no es claro y los registros son de m·s de 20 aÒos</li></ul>5) Huesos de la especie encontrados en la isla, edad no est· clara<br/>6) Evaluaciones recientes pueden haber ocurrido pero la opiniÛn del experto no es clara y no se han publicado o compartido datos</div><br/><span id="mr_present_deficient_toggle">[+]</span><span class="definitionName" id="mr_present_deficient" onclick="toggleDefinition(this.id)">Datos Deficientes</span><div class="definitionSub" id="mr_present_deficient_sub">DefiniciÛn: Isla con especies X registrada como "deficiente de datos" o "anidamiento potencial" para estado historico de anidamiento y estado que no ha sido actualizado en los ˙ltimos 20 aÒos. </p>1) Sin datos suficientes para extrapolar la ubicaciÛn exacta de la isla; el anidamiento en la isla no ha sido proporcionado en datos o en comunicaciones con expertos<br/>2) Datos de los ˙ltimos 20 aÒos no est·n disponibles; por ejemplo:<ul><li>Datos no compartidos, registros no publicados o que no se pueden accesar, no hay respuesta de expertos; no ha sido posible encontrar ninguna informaciÛn en monitoreos o registros, etc.</li><li>Si un experto sospecha anidamiento pero los datos no son claros o contradictorios</li></ul></div><br/><span id="mr_present_extirpated_toggle">[+]</span><span class="definitionName" id="mr_present_extirpated" onclick="toggleDefinition(this.id)">Extirpado</span><div class="definitionSub" id="mr_present_extirpated_sub">DefiniciÛn: extirpaciÛn confirmada de la isla. Registro de "extirpada" en notas y cualquier informaciÛn sobre cuando fue observada/monitoreada la ˙ltima vez.<br/>** Debe ser confirmada o anidamiento posible en el pasado **</div><br/><span id="mr_present_extinct_toggle">[+]</span><span class="definitionName" id="mr_present_extinct" onclick="toggleDefinition(this.id)">Extinta</span><div class="definitionSub" id="mr_present_extinct_sub">DefiniciÛn: Actualmente listada como Extinta o Extinta en Vida Silvestre por la UICN, pero se reprodujo antes de su extinciÛn en la isla (no usar si la especie existe en vida sivestre en otro lugar)</div></div><br/><strong><em>Estado historico de anidamiento - ultimos 21-200 aÒos : &lt;1990</em></strong><div class="definition"><span id="mr_historic_confirmed_toggle">[+]</span><span class="definitionName" id="mr_historic_confirmed" onclick="toggleDefinition(this.id)">Confirmado</span><div class="definitionSub" id="mr_historic_confirmed_sub">DefiniciÛn: Mismo criterio y notas que para estado de reproducciÛn actual pero usado SOLO si la especie NO HA SIDO CONFIRMADA en el presente. Si la especie es confirmada en el presente, usar NA como estado en el pasado.</div><br/><span id="mr_historic_probable_toggle">[+]</span><span class="definitionName" id="mr_historic_probable" onclick="toggleDefinition(this.id)">Probable</span><div class="definitionSub" id="mr_historic_probable_sub">DefiniciÛn: Mismo critero y notas que para estado de reproducciÛn actual pero usado SOLO si la especie NO HA SIDO CONFIRMADA en le presente. Si la especie es confirmada en el presente, usar NA como estado en el pasado.</div><br/><span id="mr_historic_potential_toggle">[+]</span><span class="definitionName" id="mr_historic_potential" onclick="toggleDefinition(this.id)">Potencial</span><div class="definitionSub" id="mr_historic_potential_sub">DefiniciÛn: Mismo critero y notas que para estado de reproducciÛn actual pero usado SOLO si la especie NO HA SIDO CONFIRMADA en le presente. Si la especie es confirmada en el presente, usar NA como estado en el pasado.<br />1) Criterios extra/notas<ul><li>Si un experto o publicaciÛn confirma anidamiento pasado pero el registro/cuenta de tipo de evidencia o aÒo del record a˙n no est· claro.</li><li>EspecÌmenes colectados en aÒos pasados pero evidencia de anidamiento no ha sido registrada o determinada.</li><li>Expertos o literatura confirma que la especies fue observada en la isla &gt; 1990 pero anidamiento nunca ha sido descrito (y NO es un endÈmico de una ˙nica isla).</li></ul></div><br/><span id="mr_historic_deficient_toggle">[+]</span><span class="definitionName" id="mr_historic_deficient" onclick="toggleDefinition(this.id)">Deficiente de datos</span><div class="definitionSub" id="mr_historic_deficient_sub">DefiniciÛn: Mismo critero y notas que para estado de reproducciÛn actual pero usado SOLO si la especie NO HA SIDO CONFIRMADA en le presente. Si la especie es confirmada en el presente, usar NA como estado en el pasado.<br />1) Criterios extra/notas<ul><li>Datos de anidamiento de los ˙ltimos 21 - 200 aÒos no est·n disponibles/no son claros</li><li>Datos no compartidos, registros no publicados que no se pueden accesar, no hay respuesta de expertos o la informaciÛn suplementada no es clara/contradictoria; no ha sido posible encontrar informaciÛn en monitoreos o registros.</li></ul></div><br/><span id="mr_historic_na_toggle">[+]</span><span class="definitionName" id="mr_historic_na" onclick="toggleDefinition(this.id)">No aplicable (NA)</span><div class="definitionSub" id="mr_historic_na_sub">1) Especie listada como "CONFIRMADA" para el estado reproductivo actual<br />2) Especie translocada a isla actual pero sin registro historico allÌ.</div></div></div>'
}

var config_byDijitId_es = {
	"searchContentDiv": "B˙squeda",
	"resultsContentDiv": "Res˙ltado",
	"islandContentDiv": "Detalles de la Isla",
	"ovContentDiv": "VisiÛn General del Mapa",
	"geography": "... por ubicaciÛn geogr·fica",
	"threatened": "... por especies amenazadas",
	"invasive": "... por especies invasoras",
	"searchButton": "Correr b˙squeda", 
	"clearButton": "Limpiar b˙squeda",
	"printButton": "Exportar",
	"csvButton": "Exportar",
	"infoDetails": "Isla",
	"infoThreatened": "Amenazadas",
	"infoInvasive": "Invasoras",
	"about": "Sobre la Base de Datos de Erradicaciones de Especies Invasoras",
	"news": "Noticias",
	"disclaimer": "Descargo de Responsabilidad",
	"species": "La Especies",
	"termsOfUse": "Condiciones de uso",
	"errors": "CÛmo ayudar",
	"partners": "Socios",	
	"Letter": "Carta",
	"csvContinueButton": "Continuar",
	"printContinueButton": "Continuar",
	"splash_language_spanish_tooltip": "EspaÒol",
	"splash_language_english_tooltip": "InglÈs",
	"searchTool_tooltip": "Pulse para abrir/cerrar la ventana de b˙squeda personalizada.",
	"resultsTool_tooltip": "Pulse para abrir/cerrar la ventana de resultados.",
	"islandsTool_tooltip": "Pulse para abrir/cerrar la ventana de detalles de isla.",
	"csvTool_tooltip": "Pulse para exportar o bajar el archivo .csv de la tabla de resultados.",
	"printTool_tooltip": "Pulse para exportar y bajar el archivo el mapa de alta resoluciÛn.",
	"basemap_tooltip": "Pulse para cambiar el mapa base.",
	"overview_tooltip": "Pulse para abrir/cerrar la ventana de visiÛn general del mapa.",
	"zoomfull_tooltip": "Pulse para ampliar el mapa a m·xima escala.",
	"zoomin_tooltip": "Pulse para ampliar el mapa usando una extensiÛn personalizada.", 
	"splitter_tooltip": "Pulse y arrastre para aumentar o disminuir la tabla visible.",
	"close_tooltip": "Pulse para mostrar u ocultar la tabla.",
	"search_tooltip": "Construir una b˙squeda.",
	"results_tooltip": "Res˙ltados de su b˙squeda.",
	"island_tooltip": "InformaciÛn detallada de una isla especÌfica.",
	"r_breeding_tooltip": "May˙s + pulse para definiciones completas de Estado Crianza.",
	"experts_tooltip": "Pulse para obtener una lista de expertos que contribuyen y el equipo de recolecciÛn de datos TIB.",
	"donate_tooltip": "Pulse para donar hacia el desarrollo TIB a travÈs del sitio Island Conservation Paypal.",
	"r_threatened_on_islands": "... islas con especies amenazadas: 0",
	"r_invasives_on_islands": "... islas con especies invasoras: 0"
}
